Repository opendatadiscovery/odd-platform, pull requests merged in 2021-12, with the labels that each got.

#279 Structure TSVector is not being calculated if field doesn't contain labels
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: bug, backend

#284 Feature/odd tracing gateway integration
  .github/workflows/build.yaml
  odd-platform-api/build.gradle
Labels: enhancement, backend

#281 Implement endpoint for getting dependent objects alerts in AlertContr…
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/AlertController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertServiceImpl.java
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
Labels: enhancement, backend

#288 Update README.md
  README.md
Labels: enhancement, chore

#292 Drop dependencies from lineage table in Ingestion API
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/IngestionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_17__add_establisher_into_lineage.sql
Labels: bug, backend

#289 Delete label relations after label deleted
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepositoryImpl.java
Labels: bug, backend

#299 Bugfix: Fixed bug with simultaneous oddrn and connectionUrl in payload.
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
Labels: bug, frontend

#302 Fast fix for lineage for microservices
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
Labels: bug, frontend, bugfix

#303 Permit healthcheck endpoint
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/LoginFormSecurityConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/OAuthSecurityConfiguration.java
Labels: bug, backend

#304 Feature/data input type support
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityAttributes.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityDetailsDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityIngestionDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntitySubtype.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataInputAttributes.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/EnrichedDataEntityIngestionDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/IngestionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_20__api_call_support.sql
  odd-platform-specification/components.yaml
  odd-platform-ui/package-lock.json
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDataInputStats/OverviewDataInputStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStatsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStatsStyles.ts
  odd-platform-ui/src/redux/interfaces/dataentities.ts
  odd-platform-ui/src/redux/reducers/dataentities.reducer.ts
Labels: enhancement, backend, frontend

#307 Implemented EntitiesListModal component.
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDataConsumerStats/OverviewDataConsumerStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDataInputStats/OverviewDataInputStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStats.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapperStyles.ts
  odd-platform-ui/src/components/shared/EntitiesListModal/EntitiesListModal.tsx
  odd-platform-ui/src/components/shared/EntitiesListModal/EntitiesListModalStyles.ts
Labels: enhancement, frontend, feature request, bugfix

#313 Fix duplicate fetching and ingestion of specific attributes
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/IngestionMapperImpl.java
Labels: bug, backend

#311 Bugfix: Datasource form validation.
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
Labels: bug, frontend, bugfix

#314 Fix nested list in specific_attributes
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/IngestionMapperImpl.java
Labels: bug, backend

#316 Uplift Ingestion Contract
  odd-platform-api/gradle.properties
Labels: bug, backend

#318 Remove logic of lowercasing oddrns
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/IngestionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
Labels: bug, backend

#319 Fix missing 'FROM' clause
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: bug, backend

#320 Bugfix: Lineage cycle dependency
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStatsStyles.ts
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/lib/helpers.ts
  odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
Labels: bug, frontend, WIP, bugfix

#283 Search page refactored to styled.
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeletonItem/SearchResultsSkeletonItem.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeletonItem/SearchResultsSkeletonItemStyles.ts
  odd-platform-ui/src/components/Search/Results/SearchTabsSkeleton/SearchTabsSkeleton.tsx
  odd-platform-ui/src/components/Search/Results/SearchTabsSkeleton/SearchTabsSkeletonStyles.ts
  odd-platform-ui/src/components/Search/Search.tsx
  odd-platform-ui/src/components/Search/SearchContainer.tsx
  odd-platform-ui/src/components/Search/SearchStyles.ts
Labels: enhancement, frontend

#287 Search filters refactored to styled.
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItem.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemContainer.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemStyles.ts
  odd-platform-ui/src/components/Search/Filters/FilterItem/SelectedFilterOption/SelectedFilterOption.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SelectedFilterOption/SelectedFilterOptionStyles.ts
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItemContainer.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItemStyles.ts
  odd-platform-ui/src/components/Search/Filters/Filters.tsx
  odd-platform-ui/src/components/Search/Filters/FiltersContainer.tsx
  odd-platform-ui/src/components/Search/Filters/FiltersStyles.ts
Labels: enhancement, frontend

#325 Dataset Field update doesn't update TSVectors
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityDimensionsDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
Labels: bug, backend

#293 LDAP authentication
  README.md
  docker/docker/examples/ldap.yml
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/LDAPSecurityConfiguration.java
  odd-platform-api/src/main/resources/application.yml
Labels: enhancement, backend, chore

#326 Fix NPE in Ingestion API
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
Labels: bug, backend

#328 Fix alerts totals
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
Labels: bug, backend

#329 Actualize demo.yaml
  docker/.env
  docker/README.md
  docker/demo.yaml
Labels: documentation, enhancement, chore

#322 Collapse Lineage nodes into the DEGs
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityLineageStreamDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNodeStyles.ts
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/GroupedEntitiesListModal/GroupedEntitiesListModal.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/GroupedEntitiesListModal/GroupedEntitiesListModalStyles.ts
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/NodeListButton/NodeListButton.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
  odd-platform-ui/src/redux/interfaces/dataentityLineage.ts
  odd-platform-ui/src/redux/interfaces/graph.ts
  odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
Labels: enhancement

#331 Disable BIC alerts for microservices
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
Labels: backend

#334 Fixed bug with updating local lineage state
  odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
Labels: bug, frontend, bugfix
