Repository opendatadiscovery/odd-platform, pull requests merged in 2021-10, with the labels that each got.

#139 Search API: order ranking bug
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: bug, enhancement, backend

#148 Set JIB created_at label to 'USE_CURRENT_TIMESTAMP'
  odd-platform-api/build.gradle
Labels: bug, backend

#145 OTEL integration
  dev/docker-compose.yaml
  dev/requests/data/glue.json
  docker/config/alert_rules.yaml
  docker/config/alertmanager.yaml
  docker/config/otel_collector.yaml
  docker/config/prometheus.yaml
  docker/demo.yaml
  odd-platform-api/build.gradle
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/com/provectus/oddplatform/config/MetricExporterConfiguration.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/config/ODDPlatformConfiguration.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/config/properties/MetricExporterProperties.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/controller/AlertManagerController.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/EnrichedDataEntityIngestionDto.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/ExternalAlert.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/AlertService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/AlertServiceImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/MetricService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/MetricServiceImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/NoOpMetricService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/dto/MetricDataTriplet.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/BinaryDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/BooleanDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/ComplexDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/DatasetFieldMetricExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/DatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/DatasetMetricExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/DatetimeDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/ExtractorUtils.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/IntegerDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/MetricExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/NumberDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/StringDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/TaskRunMetricExtractor.java
  odd-platform-api/src/main/resources/application.yml
Labels: enhancement, backend

#217 Change ArgoCD change command in GH Actions job
  .github/workflows/build.yaml
Labels: enhancement, infrastructure

#219 Search API: Take facets conditions into account when the query is present
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: bug, backend
