Repository opendatadiscovery/odd-platform, pull requests merged in 2021-08, with the labels that each got.

#58 Added expectations to dataQA tests.
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestitemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/shared/PopUpMenuByHover/PopUpMenuByHoverStyles.ts
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
Labels: enhancement

#60 Dataset structure item view bugfix
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItem.tsx
Labels: bug

#67 Home Page: Alerts widget
  odd-platform-ui/src/components/Alerts/Alerts.tsx
  odd-platform-ui/src/components/Alerts/AlertsContainer.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertListSkeleton/AlertListSkeleton.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertListSkeleton/AlertListSkeletonStyles.ts
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsListContainer.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholder.tsx
  odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholderStyles.ts
  odd-platform-ui/src/components/shared/Icons/EmptyIcon.tsx
  odd-platform-ui/src/lib/paths.ts
  odd-platform-ui/src/redux/actions/alert.actions.ts
  odd-platform-ui/src/redux/reducers/alerts.reducer.ts
Labels: enhancement, frontend

#70 Add listAll method in DataSource API
  odd-platform-api/src/main/java/com/provectus/oddplatform/controller/DataSourceController.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DataSourceService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DataSourceServiceImpl.java
  odd-platform-specification/openapi.yaml
Labels: backend, enhancement

#76 Test reports page skeleton
  odd-platform-ui/src/components/DataEntityDetails/TestReport/DatasetTestReportSkeleton/DatasetTestReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/DatasetTestReportSkeleton/DatasetTestReportSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewSkeleton/TestReportDetailsOverviewSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemSkeleton/TestReportItemSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemSkeleton/TestReportItemSkeletonStyles.ts
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
Labels: enhancement

#48 Implemented placeholder for search results tabs
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Results/ResultsContainer.tsx
  odd-platform-ui/src/components/Search/Results/SearchTabsSkeleton/SearchTabsSkeleton.tsx
  odd-platform-ui/src/components/Search/Results/SearchTabsSkeleton/SearchTabsSkeletonStyles.ts
  odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabsStyles.ts
  odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
Labels: enhancement

#82 Dataset structure skeleton
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureSkeleton/DatasetStructureSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureSkeleton/DatasetStructureSkeletonStyles.ts
Labels: enhancement

#81 DataEntity details overview and data quality report skeleton
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsSkeleton/DataEntityDetailsSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsSkeleton/DataEntityDetailsSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportSkeleton/OverviewDataQualityReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportSkeleton/OverviewDataQualityReportSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewSkeleton/OverviewSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewSkeleton/OverviewSkeletonStyles.ts
Labels: enhancement

#80 Created labels list skeleton
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsListSkeleton/LabelsListSkeleton.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsListSkeleton/LabelsListSkeletonStyles.ts
  odd-platform-ui/src/redux/selectors/labels.selectors.ts
Labels: enhancement

#79 Created owners list skeleton
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersListSkeleton/OwnersListSkeleton.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersListSkeleton/OwnersListSkeletonStyles.ts
Labels: enhancement

#75 Tags list page skeleton
  odd-platform-ui/src/components/Management/TagsList/TagListSkeleton/TagListSkeleton.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
Labels: enhancement

#74 Datasources page skeleton
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListSkeleton/DataSourcesListSkeleton.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListSkeleton/DataSourcesListSkeletonStyles.ts
  odd-platform-ui/src/redux/selectors/datasources.selectors.ts
  odd-platform-ui/src/redux/selectors/mainContentLoader.selectors.ts
Labels: enhancement

#84 Add Skeleton Wrapper.
  odd-platform-ui/src/components/Alerts/AlertsList/AlertListSkeleton/AlertListSkeleton.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertSkeletonItem/AlertSkeletonItem.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertSkeletonItem/AlertSkeletonItemStyles.ts
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsSkeleton/DataEntityDetailsSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureSkeleton/DatasetStructureSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewSkeleton/OverviewSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/DatasetTestReportSkeleton/DatasetTestReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryItemSkeleton/TestReportDetailsHistoryItemSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryItemSkeleton/TestReportDetailsHistoryItemSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistorySkeleton/TestReportDetailsHistorySkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewSkeleton/TestReportDetailsOverviewSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemSkeleton/TestReportItemSkeleton.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceSkeletonItem/DataSourceSkeletonItem.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceSkeletonItem/DataSourceSkeletonItemStyles.ts
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListSkeleton/DataSourcesListSkeleton.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsListSkeleton/LabelsListSkeleton.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsSkeletonItem/LabelsSkeletonItem.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsSkeletonItem/LabelsSkeletonItemStyles.ts
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersListSkeleton/OwnersListSkeleton.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersSkeletonItem/OwnersSkeletonItem.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersSkeletonItem/OwnersSkeletonItemStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagListSkeleton/TagListSkeleton.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsSkeletonItem/TagsSkeletonItem.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeleton/SearchResultsSkeleton.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeletonItem/SearchResultsSkeletonItem.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeletonItem/SearchResultsSkeletonItemStyles.ts
  odd-platform-ui/src/components/shared/AlertStatusItem/AlertStatusItem.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
  odd-platform-ui/src/components/shared/SkeletonWrapper/SkeletonWrapper.tsx
  odd-platform-ui/src/components/shared/SkeletonWrapper/SkeletonWrapperStyles.ts
  odd-platform-ui/src/lib/constants.ts
  odd-platform-ui/src/lib/helpers.ts
Labels: enhancement, frontend

#87 Add main overview page content placeholder.
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/Overview/OverviewSkeleton/OverviewSkeleton.tsx
  odd-platform-ui/src/components/Overview/OverviewSkeleton/OverviewSkeletonStyles.ts
  odd-platform-ui/src/components/Overview/TopTagsList/TopTagsList.tsx
  odd-platform-ui/src/components/Overview/TopTagsList/TopTagsListContainer.tsx
  odd-platform-ui/src/redux/selectors/mainContentLoader.selectors.ts
Labels: enhancement, frontend

#86 Feature / lineage content loader
  odd-platform-ui/src/components/Search/Filters/Filters.tsx
  odd-platform-ui/src/components/Search/Filters/FiltersContainer.tsx
  odd-platform-ui/src/components/Search/Filters/FiltersStyles.ts
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphContainer.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphStyles.ts
  odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabsStyles.ts
  odd-platform-ui/src/components/shared/CircularProgressLoader/CircularProgressLoader.tsx
  odd-platform-ui/src/components/shared/CircularProgressLoader/CircularProgressLoaderStyles.ts
Labels: enhancement, frontend

#85 Add circular progress loader component.
  odd-platform-ui/src/components/Search/Filters/Filters.tsx
  odd-platform-ui/src/components/Search/Filters/FiltersContainer.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
Labels: enhancement, frontend

#77 Add search suggestion API
  odd-platform-api/src/main/java/com/provectus/oddplatform/controller/SearchController.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/SearchService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/SearchServiceImpl.java
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityList.tsx
  odd-platform-ui/src/components/Overview/OverviewStyles.ts
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholderStyles.ts
  odd-platform-ui/src/components/shared/MainSearch/MainSearch.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchContainer.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchStyles.ts
  odd-platform-ui/src/redux/actions/dataentitySearch.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/dataentitiesSearch.reducer.ts
  odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
  odd-platform-ui/src/redux/thunks/alerts.thunks.ts
  odd-platform-ui/src/redux/thunks/dataentitiesSearch.thunks.ts
Labels: enhancement, backend

#72 WIP: Added suggestions list to search bar.
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityList.tsx
  odd-platform-ui/src/components/Overview/OverviewStyles.ts
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholderStyles.ts
  odd-platform-ui/src/components/shared/MainSearch/MainSearch.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchContainer.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchStyles.ts
  odd-platform-ui/src/redux/actions/dataentitySearch.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/dataentitiesSearch.reducer.ts
  odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
  odd-platform-ui/src/redux/thunks/alerts.thunks.ts
  odd-platform-ui/src/redux/thunks/dataentitiesSearch.thunks.ts
Labels: enhancement, frontend, WIP

#94 Enable FTS prefix matching
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: bug

#88 Created overflow tooltip component.
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItemStyles.ts
  odd-platform-ui/src/components/shared/PopUpMenuByClick/PopUpMenuByClick.tsx
  odd-platform-ui/src/components/shared/PopUpMenuByClick/PopUpMenuByClickStyles.ts
  odd-platform-ui/src/components/shared/PopUpMenuByHover/PopUpMenuByHover.tsx
  odd-platform-ui/src/components/shared/PopUpMenuByHover/PopUpMenuByHoverStyles.ts
  odd-platform-ui/src/components/shared/Tooltip/Tooltip.tsx
  odd-platform-ui/src/components/shared/Tooltip/TooltipStyles.ts
Labels: enhancement, frontend, chore

#90 Added unknown sources/targets count.
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStatsStyles.ts
  odd-platform-ui/src/redux/interfaces/dataentities.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/dataentities.reducer.ts
Labels: enhancement

#89 Added global error page to search/data entity details.
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/Search/Search.tsx
  odd-platform-ui/src/components/Search/SearchContainer.tsx
  odd-platform-ui/src/components/shared/AppErrorPage/AppErrorPage.tsx
  odd-platform-ui/src/components/shared/AppErrorPage/AppErrorPageContainer.tsx
  odd-platform-ui/src/components/shared/AppErrorPage/AppErrorPageStyles.ts
  odd-platform-ui/src/redux/actions/dataentity.actions.ts
  odd-platform-ui/src/redux/interfaces/loader.ts
  odd-platform-ui/src/redux/reducers/loader-reducer.ts
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
  odd-platform-ui/src/redux/selectors/loader-selectors.ts
  odd-platform-ui/src/redux/thunks/base.thunk.ts
Labels: enhancement

#92 Added empty content placeholder to management section and alerts.
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlerts.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsListStyles.ts
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersListStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsListStyles.ts
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityList.tsx
  odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholderStyles.ts
Labels: enhancement

#96 Bugfix: search creation empty page
  odd-platform-ui/src/components/App.tsx
  odd-platform-ui/src/components/Search/Search.tsx
Labels: bug, frontend

#97 Fix FTS ranking
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/util/FTSVectorizer.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/util/JooqFTSVectorizer.java
Labels: bug

#100 Synchronize ODD Spec and ODD Platform OpenAPI (DataSetFieldType's type enum)
  odd-platform-specification/components.yaml
Labels: bug
