Repository opendatadiscovery/odd-platform, pull requests merged in 2021-11, with the labels that each got.

#223 BugFix: Style Fixes
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistoryStyles.ts
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityList.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTab/AppLinkTab.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTab/AppTab.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTab/TabStyles.ts
  odd-platform-ui/src/components/shared/AppTabs/AppTabLabel/AppTabLabel.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabLabel/AppTabLabelStyles.ts
  odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
  odd-platform-ui/src/components/shared/NumberFormatted/NumberFormatted.tsx
Labels: bug, frontend, bugfix

#231 Update README.md with slack link
  README.md
Labels: chore

#229 Feature: Data Entity card preview on the search page
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewContainer.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewStyles.ts
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemStyles.ts
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Results/ResultsContainer.tsx
  odd-platform-ui/src/components/Search/Results/ResultsStyles.ts
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltip.tsx
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltipStyles.ts
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/lib/constants.ts
  odd-platform-ui/src/redux/interfaces/datasetStructure.ts
  odd-platform-ui/src/theme/palette.ts
Labels: enhancement, frontend

#216 Enhancement: AutocompleteSuggestion, JSS to styled.
  odd-platform-ui/src/components/shared/AutocompleteSuggestion/AutocompleteSuggestion.tsx
  odd-platform-ui/src/components/shared/AutocompleteSuggestion/AutocompleteSuggestionStyles.ts
Labels: enhancement, frontend

#247 Prometheus metrics export
  odd-platform-api/build.gradle
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/com/provectus/oddplatform/config/ResourceProviderWebFilter.java
  odd-platform-api/src/main/resources/application.yml
Labels: enhancement, backend, infrastructure

#248 increase gradle to 7.3 and java to 17
  .github/workflows/build.yaml
  .github/workflows/codestyle.yaml
  .github/workflows/release-build.yaml
  gradle/wrapper/gradle-wrapper.properties
  odd-platform-api-contract/build.gradle
  odd-platform-api-contract/gradle/wrapper/gradle-wrapper.jar
  odd-platform-api-contract/gradle/wrapper/gradle-wrapper.properties
  odd-platform-api-contract/gradlew
  odd-platform-api-contract/gradlew.bat
  odd-platform-api/build.gradle
  odd-platform-api/gradle/wrapper/gradle-wrapper.jar
  odd-platform-api/gradle/wrapper/gradle-wrapper.properties
  odd-platform-api/gradlew
  odd-platform-api/gradlew.bat
  odd-platform-api/jooq.generate.gradle
Labels: backend

#232 Unite DatasetFields' update requests into one
  odd-platform-api/src/main/java/com/provectus/oddplatform/controller/DatasetFieldController.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/DatasetFieldDto.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DatasetFieldApiMapper.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DatasetFieldApiMapperImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetFieldRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetStructureRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/LabelRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DatasetFieldService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DatasetFieldServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_16__add_datasetfield_oddrn_index.sql
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditFormStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocompleteContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/InternalDescriptionFormDialog/InternalDescriptionFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/InternalDescriptionFormDialog/InternalDescriptionFormDialogContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/InternalDescriptionFormDialog/InternalDescriptionFormDialogStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/LabelsEditForm/LabelsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/LabelsEditForm/LabelsEditFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/LabelsEditForm/LabelsEditFormStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/shared/LabelItem/LabelItem.tsx
  odd-platform-ui/src/components/shared/LabelItem/LabelItemStyles.ts
  odd-platform-ui/src/redux/actions/datasetStructure.actions.ts
  odd-platform-ui/src/redux/interfaces/datasetStructure.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/datasetStructure.reducer.ts
  odd-platform-ui/src/redux/selectors/datasetStructure.selectors.ts
  odd-platform-ui/src/redux/thunks/datasetStructure.thunks.ts
Labels: enhancement, backend, frontend

#250 Fixing NPE in DataEntityMapperImpl
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DataEntityMapperImpl.java
Labels: bug, backend, bugfix

#241 Enhancement: Dataset structure optimization
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTable.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/shared/AppIconButton/AppIconButton.tsx
  odd-platform-ui/src/components/shared/AppPopover/AppPopover.tsx
  odd-platform-ui/src/components/shared/AppPopover/AppPopoverStyles.ts
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltip.tsx
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltipStyles.ts
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltipStyles.tsx
  odd-platform-ui/src/components/shared/Icons/InformationIcon.tsx
Labels: bug, enhancement, frontend

#254 Bugfix/datasetfield datetime stats deserialize
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/LabelRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/TagRepositoryImpl.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
Labels: bug, backend, frontend, bugfix

#258 Make checkstyle build application
  .github/workflows/codestyle.yaml
Labels: enhancement, backend

#260 Bugfix/datasetfield datetime stats deserialize
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/LabelRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/TagRepositoryImpl.java
Labels: bug, backend

#262 Bugfix: Preview icon styles fix.
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewStyles.ts
Labels: bug, frontend

#266 CI env updates
  .github/workflows/build.yaml
  .github/workflows/codestyle.yaml
  .github/workflows/release-build.yaml
Labels: infrastructure

#270 use maven central for ingestion contract
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/com/provectus/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/DataEntityIngestionDto.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DatasetFieldMapper.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DatasetFieldMapperImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/IngestionMapper.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/IngestionMapperImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/BinaryDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/BooleanDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/ComplexDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/DatasetFieldMetricExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/DatetimeDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/IntegerDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/NumberDatasetFieldStatExtractor.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/metric/extractors/StringDatasetFieldStatExtractor.java
Labels: enhancement, backend

#271 Remove credentials from workflows
  .github/workflows/build.yaml
  .github/workflows/codestyle.yaml
  .github/workflows/release-build.yaml
Labels: enhancement, backend

#267 Enhancement: shared components to styled
  odd-platform-ui/.eslintignore
  odd-platform-ui/config-overrides.js
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureList.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneralStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTags.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTagsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipFormStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportStyles.ts
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemStyles.ts
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListStyles.ts
  odd-platform-ui/src/components/Overview/TopTagsList/TopTagsList.tsx
  odd-platform-ui/src/components/Overview/TopTagsList/TopTagsListContainer.tsx
  odd-platform-ui/src/components/Overview/TopTagsList/TopTagsListStyles.ts
  odd-platform-ui/src/components/Search/Results/ResultsStyles.ts
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarContainer.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarStyles.ts
  odd-platform-ui/src/components/shared/ConfirmationDialog/ConfirmationDialog.tsx
  odd-platform-ui/src/components/shared/ConfirmationDialog/ConfirmationDialogStyles.ts
  odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholder.tsx
  odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholderStyles.ts
  odd-platform-ui/src/components/shared/Icons/EmptyIcon.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/components/shared/MainSearch/MainSearch.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchContainer.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchStyles.ts
  odd-platform-ui/src/components/shared/SkeletonWrapper/SkeletonWrapper.tsx
  odd-platform-ui/src/components/shared/SkeletonWrapper/SkeletonWrapperStyles.ts
  odd-platform-ui/src/components/shared/TagItem/TagItem.tsx
  odd-platform-ui/src/components/shared/TagItem/TagItemStyles.ts
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItem.tsx
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItemStyles.ts
  odd-platform-ui/src/index.tsx
  odd-platform-ui/src/theme/interfaces.ts
  odd-platform-ui/src/theme/palette.ts
  odd-platform-ui/tsconfig.base.json
  odd-platform-ui/tsconfig.json
Labels: enhancement, frontend
