Repository opendatadiscovery/odd-platform, pull requests merged in 2021-09, with the labels that each got.

#108 Fix CI build issue
  .github/workflows/build.yaml
  .github/workflows/release-build.yaml
  odd-platform-ui/build.gradle
  odd-platform-ui/package.json
Labels: bug

#118 Change http code for EntityAlreadyExistsException
  odd-platform-api/src/main/java/com/provectus/oddplatform/exception/EntityAlreadyExists.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/exception/EntityAlreadyExistsException.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/specification/CreatableWithSoftDelete.java
Labels: backend, bugfix

#120 Preserve dataset structure descriptions and labels
  dev/.env
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/DataEntityIngestionDtoSplit.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/DatasetFieldDto.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DatasetFieldMapper.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DatasetFieldMapperImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DatasetVersionMapperImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/AlertRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/AlertRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetFieldRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetStructureRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetStructureRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/main/resources/db/migration/V0_0_9__normalize_dataset_structure.sql
Labels: enhancement, backend, WIP

#114 BugFix: when go to the catalog page, old search results are shown
  odd-platform-ui/src/components/Search/Results/Results.tsx
Labels: bug, frontend, bugfix

#121 Data quality test details: info about last run and expectations and test runs history page
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunItem/QualityTestRunItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunItem/QualityTestRunItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistoryContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistoryStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItem.tsx
  odd-platform-ui/src/lib/paths.ts
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
Labels: enhancement, frontend

#124 Bug fix: DataEntity tabs move to the page of the previous entity
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
Labels: bug, enhancement, frontend

#116 Data entity view counters
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_10__add_counters.sql
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
Labels: enhancement, backend, frontend

#125 Ingestion API: properly update fields when ingesting
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetFieldRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DatasetStructureRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionServiceImpl.java
Labels: bug

#109 Feature: split lineage streams
  .github/workflows/codestyle.yaml
  build.gradle
  dev/requests/data/prod_glue.json
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/com/provectus/oddplatform/controller/DataEntityController.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/LineageStreamKind.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/StreamKind.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/util/JooqFTSVectorizer.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DataEntityService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-specification/openapi.yaml
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/LineageContainer.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphContainer.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLink.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNodeStyles.ts
  odd-platform-ui/src/redux/actions/dataentityLineage.actions.ts
  odd-platform-ui/src/redux/interfaces/dataentityLineage.ts
  odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
  odd-platform-ui/src/redux/selectors/dataentityLineage.selectors.ts
  odd-platform-ui/src/redux/thunks/dataentityLineage.thunks.ts
Labels: enhancement, backend, frontend

#126 Finals validation for checkstyle
  config/checkstyle/checkstyle.xml
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionServiceImpl.java
Labels: enhancement, backend

#107 Logout feature
  .github/workflows/release-build.yaml
  odd-platform-api/src/main/java/com/provectus/oddplatform/auth/CognitoOidcLogoutSuccessHandler.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/config/LoginFormSecurityConfiguration.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/config/OAuthSecurityConfiguration.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-ui/Dockerfile
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarStyles.ts
Labels: enhancement, backend, frontend

#135 BugFix: "broken" test runs count
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/redux/interfaces/dataQualityTest.ts
  odd-platform-ui/src/redux/reducers/dataQualityTest.reducer.ts
Labels: bug, frontend

#131 BugFix: Lineage in Safari
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphStyles.ts
Labels: bug, frontend

#136 Tag counters
  config/checkstyle/checkstyle.xml
  odd-platform-api/src/main/java/com/provectus/oddplatform/ODDPlatformApplication.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/controller/TagController.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/dto/TagDto.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/TagMapper.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/mapper/TagMapperImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/TagRepository.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/repository/TagRepositoryImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/TagService.java
  odd-platform-api/src/main/java/com/provectus/oddplatform/service/TagServiceImpl.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/Search/Results/Results.tsx
Labels: enhancement, backend
