Repository opendatadiscovery/odd-platform, pull requests merged in 2022-11, with the labels that each got.

#1054 New tests filters
  docker/injector/datasources/datasources.json
  docker/injector/samples/11_etl_aqa.json
  docker/injector/samples/12_oracle_fl_aqa.json
  docker/injector/samples/13_oracle_ingestion_aqa.json
  docker/injector/samples/14_airflow_ingestion_aqa.json
  tests/features/filters/filters.spec.ts
  tests/features/owners/add-owner.spec.ts
  tests/features/tags/add-tag.spec.ts
  tests/features/tags/change-tag.spec.ts
  tests/features/tags/delete-tag.spec.ts
  tests/ui/pages/catalog/catalog-page.ts
  tests/ui/pages/data_entity/data_entity.page.ts
  tests/ui/pages/data_entity/overview.page.ts
  tests/ui/pages/index.ts
  tests/ui/pages/management/tags-page.ts
  tests/ui/pages/shared/top-panel.ts
  tests/ui/steps/go-to-steps.ts
Labels: kind: testing

#1076 Add `on conflict do update` in queries against 'shared' tables of Ingestion API
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveMetadataFieldRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveMetadataFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqQueryHelper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ReactiveLabelService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/TagService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/TagServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/ExternalTagIngestionRequestProcessor.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/MetadataIngestionRequestProcessor.java
  odd-platform-api/src/main/resources/db/migration/V0_0_57__change_tag_unique_constraint_semantics.sql
Labels: kind: bug, scope: backend

#1082 Bugfix: invalid hooks rendering
  odd-platform-ui/src/components/Alerts/Alerts.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItemContent/AlertItemContent.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItemContent/AlertItemContentStyles.ts
  odd-platform-ui/src/components/App.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlerts.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsHeader/DataEntityDetailsHeader.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsHeader/DataEntityDetailsHeaderStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroup/DataEntityGroupControls/DataEntityGroupControls.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsFormItem/DatasetFieldEnumsFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OwnersSection/OwnersSection.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OwnersSection/OwnershipForm/OwnershipForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/GroupItem/GroupItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/OverviewGroups.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadata.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTags.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTerms/OverviewTerms.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/components/Management/OwnerAssociations/AssociationRequestItem/ActiveAssociationRequest.tsx
  odd-platform-ui/src/components/Management/PolicyList/PolicyDetails/PolicyForm/PolicyForm.tsx
  odd-platform-ui/src/components/Management/PolicyList/PolicyItem/PolicyItem.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/OwnerAssociation/OwnerAssociationForm/OwnerAssociationForm.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Search.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/OverviewTags.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermDetails.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermDetailsHeader/TermDetailsHeader.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearch.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchHeader/TermSearchHeader.tsx
  odd-platform-ui/src/components/shared/TermItem/TermItem.tsx
  odd-platform-ui/src/components/shared/contexts/Permission/PermissionContext.ts
  odd-platform-ui/src/components/shared/contexts/Permission/PermissionProvider.tsx
  odd-platform-ui/src/components/shared/contexts/Permission/WithPermissions.tsx
  odd-platform-ui/src/components/shared/contexts/Permission/WithPermissionsProvider.tsx
  odd-platform-ui/src/lib/hooks/usePermissions.ts
  odd-platform-ui/src/redux/interfaces/alerts.ts
Labels: kind: bug, scope: frontend

#1084 Fix deadlock on activity partition creation
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/SchedulingConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/SessionConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/leaderelection/PostgreSQLLeaderElectionManager.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/leaderelection/PostgreSQLLeaderElectionManagerImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityPartitionCreationJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityTablePartitionManager.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityTablePartitionManagerImpl.java
  odd-platform-api/src/main/resources/application.yml
Labels: kind: bug, scope: backend

#1083 Implemented app info menu.
  odd-platform-ui/src/components/shared/AppMenu/AppMenu.tsx
  odd-platform-ui/src/components/shared/AppMenu/AppMenuStyles.ts
  odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItem.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppInfoMenu/AppInfoMenu.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppInfoMenu/AppInfoMenuStyles.ts
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarStyles.ts
  odd-platform-ui/src/components/shared/Icons/GitBookIcon.tsx
  odd-platform-ui/src/components/shared/Icons/GitHubIcon.tsx
  odd-platform-ui/src/components/shared/Icons/InformationIcon.tsx
  odd-platform-ui/src/components/shared/Icons/SlackIcon.tsx
  odd-platform-ui/src/components/shared/Icons/index.ts
Labels: scope: frontend, kind: feature

#1105 Allow Slack API endpoints
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/util/SecurityConstants.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/LoginFormSecurityConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/AlertManagerController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/controller/EventApiController.java
Labels: kind: bug

#1085 Added search tests
  docker/injector/datasources/datasources.json
  docker/injector/samples/14_airflow_ingestion_aqa.json
  tests/features/filters/filters.spec.ts
  tests/features/search/search.spec.ts
  tests/ui/elements/list.ts
  tests/ui/elements/text-box.ts
  tests/ui/pages/catalog/catalog-page.ts
Labels: kind: testing

#1114 Isolated e2e test environment
  .github/workflows/main-build.yaml
  .github/workflows/release-build.yaml
  .github/workflows/run-playwright-tests.yml
  .github/workflows/run-pr-tests.yaml
  build.gradle
  docker/config/injector/datasources/datasources.json
  docker/config/injector/samples/01_airflow_ingestion.json
  docker/config/injector/samples/02_bookshop_datalake_ingestion.json
  docker/config/injector/samples/03_bookshop_tr_ingestion.json
  docker/config/injector/samples/04_etl_ingestion.json
  docker/config/injector/samples/05_kafka_del_ingestion.json
  docker/config/injector/samples/06_kinesis_consumer_ingestion.json
  docker/config/injector/samples/07_kinesis_ingestion.json
  docker/config/injector/samples/08_s3_ingestion.json
  docker/config/injector/samples/09_snowflake_ingestion.json
  docker/config/injector/samples/10_ge_ingestion.json
  docker/demo.yaml
  injector/inject.py
  injector/start.sh
  odd-platform-api/build.gradle
  tests/README.md
  tests/docker/.env
  tests/docker/collector_setting_from_post.yaml
  tests/docker/docker-compose.yaml
  tests/docker/injector/datasources/datasources.json
  tests/docker/injector/samples/01_etl_aqa.json
  tests/docker/injector/samples/02_oracle_fl_aqa.json
  tests/docker/injector/samples/03_oracle_ingestion_aqa.json
  tests/docker/injector/samples/04_airflow_ingestion_aqa.json
  tests/docker/req.json
  tests/docker/up-collector.sh
  tests/docker/up-platform.sh
  tests/features/filters/filters.spec.ts
  tests/features/search/search.spec.ts
  tests/package.json
  tests/ui/pages/data_entity/overview.page.ts
Labels: kind: documentation, kind: feature, scope: infrastructure, kind: testing

#1112 Feature / Now structure version display created_at information
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/Activity/ActivityResults/ActivityItem/ActivityItem.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItemContent/AlertItemContent.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/CurrentMessage/Thread/ThreadContent/ThreadMessage/ThreadMessage.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/MessagesList/Message/Message.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityActivity/ActivityResults/ActivityItem/ActivityItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsHeader/DataEntityDetailsHeader.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldStats/DatasetFieldStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/LinkedItemsList/LinkedItem/LinkedItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunItem/TestRunItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunStatusReasonModal/TestRunStatusReasonModal.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestItem.tsx
  odd-platform-ui/src/components/Management/OwnerAssociations/AssociationRequestItem/ResolvedAssociationRequest.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermDetailsHeader/TermDetailsHeader.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermLinkedItemsList/LinkedItem/LinkedItem.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchResults/TermSearchResultItem/TermSearchResultItem.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelect.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelectStyles.ts
  odd-platform-ui/src/lib/constants.ts
  odd-platform-ui/src/lib/hooks/index.ts
  odd-platform-ui/src/lib/hooks/useAppDateTime.ts
Labels: scope: frontend, kind: feature

#1129 Data QA attributes
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsHeader/DataEntityDetailsHeader.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OwnersSection/OwnersSection.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadata.tsx
  odd-platform-ui/src/components/shared/AppInput/AppInput.tsx
  odd-platform-ui/src/components/shared/AppRadio/AppRadio.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelect.tsx
  odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx
Labels: scope: frontend, kind: testing
