Repository opendatadiscovery/odd-platform, pull requests merged in 2022-01, with the labels that each got.

#346 Delete CODE_OF_CONDUCT.MD
  CODE_OF_CONDUCT.MD
Labels: chore

#345 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: chore

#337 Optimize DataEntityDto retrieval
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/resources/application.yml
Labels: backend

#340 Remove CD ranking out of FTS
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
Labels: bug, backend

#349 FTS partial matches
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
Labels: bug, backend

#350 Bugfix: lineage updating
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/GroupedEntitiesListModal/GroupedEntitiesListModal.tsx
  odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
Labels: bug, frontend, bugfix

#352 Update maintenance badge state
  README.md
Labels: documentation, chore

#357 AppGraphLink refactor.
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphContainer.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphCrossLink/AppGraphCrossLink.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphCrossLink/AppGraphCrossLinkStyles.ts
  odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLink.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLinkStyles.ts
  odd-platform-ui/src/components/shared/AppGraph/AppGraphStyles.ts
  odd-platform-ui/src/components/shared/AppPopover/AppPopover.tsx
  odd-platform-ui/src/components/shared/AppPopover/AppPopoverStyles.ts
Labels: enhancement, scope: frontend

#360 Add necessary automation
  .github/ISSUE_TEMPLATES/bug_report.md
  .github/ISSUE_TEMPLATES/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/triage.yaml
  CONTRIBUTING.md
Labels: scope: infrastructure, kind: chore, chore

#354 Enhancement: Specific attributes for entities at results page
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemStyles.ts
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButton.tsx
  odd-platform-ui/src/components/shared/AppIconButton/AppIconButton.tsx
  odd-platform-ui/src/components/shared/AppIconButton/AppIconButtonStyles.ts
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCell.tsx
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenu.tsx
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenuStyles.ts
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellStyles.ts
  odd-platform-ui/src/theme/interfaces.ts
  odd-platform-ui/src/theme/palette.ts
Labels: kind: enhancement, scope: frontend

#370 Dataset structure table refactored to styled.
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureSkeleton/DatasetStructureSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureSkeleton/DatasetStructureSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTable.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableStyles.ts
  odd-platform-ui/src/components/shared/NumberFormatted/NumberFormatted.tsx
Labels: kind: enhancement, scope: frontend

#359 Alerts section refactored to styled.
  odd-platform-ui/src/components/Alerts/Alerts.tsx
  odd-platform-ui/src/components/Alerts/AlertsContainer.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItemStyles.ts
  odd-platform-ui/src/components/Alerts/AlertsList/AlertSkeletonItem/AlertSkeletonItem.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertSkeletonItem/AlertSkeletonItemStyles.ts
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsListContainer.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsListStyles.ts
  odd-platform-ui/src/components/Alerts/AlertsStyles.ts
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Results/ResultsStyles.ts
Labels: kind: enhancement, scope: frontend

#344 Main overview page refactored to styled components
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityList.tsx
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityListContainer.tsx
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityListStyles.ts
  odd-platform-ui/src/components/Overview/IdentityForm/Identity.tsx
  odd-platform-ui/src/components/Overview/IdentityForm/IdentityContainer.tsx
  odd-platform-ui/src/components/Overview/IdentityForm/IdentityStyles.ts
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/Overview/OverviewSkeleton/OverviewSkeleton.tsx
  odd-platform-ui/src/components/Overview/OverviewSkeleton/OverviewSkeletonStyles.ts
  odd-platform-ui/src/components/Overview/OverviewStyles.ts
  odd-platform-ui/src/components/shared/Icons/UserSyncIcon.tsx
  odd-platform-ui/src/lib/constants.ts
Labels: kind: enhancement, scope: frontend

#342 Enhancement: Management page refactored to styled components
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemStyles.ts
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceSkeletonItem/DataSourceSkeletonItem.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceSkeletonItem/DataSourceSkeletonItemStyles.ts
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListStyles.ts
  odd-platform-ui/src/components/Management/LabelsList/EditableLabelItem/EditableLabelItem.tsx
  odd-platform-ui/src/components/Management/LabelsList/EditableLabelItem/EditableLabelItemStyles.ts
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateFormContainer.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateFormItem/LabelCreateFormItem.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateFormItem/LabelCreateFormItemStyles.ts
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateFormStyles.ts
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditFormContainer.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditFormStyles.ts
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsListContainer.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsListStyles.ts
  odd-platform-ui/src/components/Management/LabelsList/LabelsSkeletonItem/LabelsSkeletonItem.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsSkeletonItem/LabelsSkeletonItemStyles.ts
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/components/Management/ManagementContainer.tsx
  odd-platform-ui/src/components/Management/ManagementStyles.ts
  odd-platform-ui/src/components/Management/NamespaceList/EditableNamespaceItem/EditableNamespaceItem.tsx
  odd-platform-ui/src/components/Management/NamespaceList/EditableNamespaceItem/EditableNamespaceItemStyles.ts
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceForm.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceFormContainer.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceFormStyles.ts
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListContainer.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListSkeleton/NamespaceListSkeleton.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListSkeleton/NamespaceListSkeletonStyles.ts
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListStyles.ts
  odd-platform-ui/src/components/Management/OwnersList/EditableOwnerItem/EditableOwnerItem.tsx
  odd-platform-ui/src/components/Management/OwnersList/EditableOwnerItem/EditableOwnerItemStyles.ts
  odd-platform-ui/src/components/Management/OwnersList/OwnerForm/OwnerForm.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnerForm/OwnerFormContainer.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnerForm/OwnerFormStyles.ts
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersListContainer.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersListStyles.ts
  odd-platform-ui/src/components/Management/OwnersList/OwnersSkeletonItem/OwnersSkeletonItem.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersSkeletonItem/OwnersSkeletonItemStyles.ts
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItem.tsx
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItemStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormContainer.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormItem/TagCreateFormItem.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormItem/TagCreateFormItemStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditFormContainer.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditFormStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsListContainer.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsListStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagsSkeletonItem/TagsSkeletonItem.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsSkeletonItem/TagsSkeletonItemStyles.ts
Labels: kind: enhancement, scope: frontend

#373 Bugfix/fixing validate dom nesting
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneralStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditForm.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceForm.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnerForm/OwnerForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabLabel/AppTabLabel.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabLabel/AppTabLabelStyles.ts
  odd-platform-ui/src/components/shared/AutocompleteSuggestion/AutocompleteSuggestion.tsx
  odd-platform-ui/src/components/shared/AutocompleteSuggestion/AutocompleteSuggestionStyles.ts
  odd-platform-ui/src/components/shared/ConfirmationDialog/ConfirmationDialog.tsx
Labels: kind: bug, scope: frontend

#368 Gitbook activity
  .gitbook.yaml
  docs/SUMMARY.md
Labels: kind: documentation, chore

#375 Refactored AppGraphNode to styled components.
  odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLink.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNodeStyles.ts
Labels: kind: enhancement, scope: frontend

#377 DataEntityDetails alerts section refactored to styled.
  odd-platform-ui/src/components/DataEntityDetails/AlertBanners/AlertBanner/AlertBanner.tsx
  odd-platform-ui/src/components/DataEntityDetails/AlertBanners/AlertBanner/AlertBannerStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/AlertBanners/AlertBanners.tsx
  odd-platform-ui/src/components/DataEntityDetails/AlertBanners/AlertBannersContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/AlertBanners/AlertBannersStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlerts.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertsSkeleton/DataEntityAlertsSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertsSkeleton/DataEntityAlertsSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertsStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormItem/TagCreateFormItem.tsx
Labels: kind: enhancement, scope: frontend

#382 Refactored to styled components DataEntityDetails sections.
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsSkeleton/DataEntityDetailsSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsSkeleton/DataEntityDetailsSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialogContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialogStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/LineageContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/LineageStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditorStyles.ts
  odd-platform-ui/src/index.tsx
Labels: kind: enhancement, scope: frontend

#383 Enhancement/data entity details to styled components
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportSkeleton/OverviewDataQualityReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportSkeleton/OverviewDataQualityReportSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescriptionContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescriptionStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadata.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadataContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadataStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewSkeleton/OverviewSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewSkeleton/OverviewSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDataConsumerStats/OverviewDataConsumerStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDataConsumerStats/OverviewDataConsumerStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDatasetStats/OverviewDatasetStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDatasetStats/OverviewDatasetStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTags.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTagsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormStyles.ts
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/shared/Icons/RowsIcon.tsx
  odd-platform-ui/src/components/shared/Icons/UserIcon.tsx
  odd-platform-ui/src/components/shared/LabelItem/LabelItem.tsx
  odd-platform-ui/src/components/shared/LabelItem/LabelItemStyles.ts
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
Labels: kind: enhancement, scope: frontend

#386 Data quality test run status reason.
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunItem/QualityTestRunItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunItem/QualityTestRunItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistoryStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunItem/TestRunItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunItem/TestRunItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunStatusReasonModal/TestRunStatusReasonModal.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunStatusReasonModal/TestRunStatusReasonModalStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistoryContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistoryStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/DatasetTestReportSkeleton/DatasetTestReportSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryItemSkeleton/TestReportDetailsHistoryItemSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryItemSkeleton/TestReportDetailsHistoryItemSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewSkeleton/TestReportDetailsOverviewSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestitemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemSkeleton/TestReportItemSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemSkeleton/TestReportItemSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportSkeleton/TestReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportStyles.ts
  odd-platform-ui/src/components/shared/AppButton/AppButtonStyles.ts
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapperStyles.ts
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItem.tsx
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItemStyles.ts
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
Labels: scope: frontend, kind: feature, enhancement

#394 Bug: Ingestion API doesn't take hollow entities into the account while persisting Data Entities
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
Labels: kind: bug, scope: backend

#395 Replace spaces with conjunction in FTS query
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
Labels: kind: bug, scope: backend

#399 Implemented support of enum fields in DatasetStructure
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DatasetFieldController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DatasetFieldDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/EnumValueMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/EnumValueMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/EnumValueService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/EnumValueServiceImpl.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/main/resources/db/migration/V0_0_25__add_dataset_field_enum_values.sql
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsEditFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsEditFormStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsFormItem/DatasetFieldEnumsFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsFormItem/DatasetFieldEnumsFormItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButtonStyles.ts
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapperStyles.ts
  odd-platform-ui/src/lib/helpers.ts
  odd-platform-ui/src/redux/actions/datasetStructure.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/datasetStructure.reducer.ts
  odd-platform-ui/src/redux/selectors/datasetStructure.selectors.ts
  odd-platform-ui/src/redux/thunks/datasetStructure.thunks.ts
  odd-platform-ui/src/theme/interfaces.ts
  odd-platform-ui/src/theme/palette.ts
Labels: scope: backend, scope: frontend, kind: feature
