Repository opendatadiscovery/odd-platform, pull requests merged in 2022-09, with the labels that each got.

#946 FE: Updating packages
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/index.tsx
  odd-platform-ui/src/lib/redux/helpers.ts
Labels: kind: enhancement, scope: frontend

#956 Add multiarch container build
  .github/workflows/main-build.yaml
  .github/workflows/release-build.yaml
  build.gradle
  odd-platform-api/build.gradle
Labels: kind: bug, scope: build

#915 Fix status report calculation
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/components/shared/NumberFormatted/NumberFormatted.tsx
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
  odd-platform-ui/src/theme/interfaces.ts
  odd-platform-ui/src/theme/palette.ts
Labels: kind: bug, scope: frontend

#912 Updated test reports, added object render
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/LinkedItemsList/LinkedListSkeleton/LinkedListSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewExpectations/OverviewExpectations.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewExpectations/OverviewExpectationsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupStats/OverviewEntityGroupStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewParametersModal/TestReportDetailsOverviewParametersModal.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewSkeleton/TestReportDetailsOverviewSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemSkeleton/TestReportItemSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportSkeleton/TestReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportStyles.ts
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceList.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeleton/SearchResultsSkeleton.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermDetails.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchResults/TermSearchResultsSkeleton/TermSearchResultsSkeleton.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButton.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButtonStyles.ts
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltip.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapperStyles.ts
  odd-platform-ui/src/components/shared/EntitiesListModal/EntitiesListModal.tsx
  odd-platform-ui/src/components/shared/ObjectRender/ObjectRender.tsx
  odd-platform-ui/src/components/shared/ObjectRender/ObjectRenderStyles.tsx
  odd-platform-ui/src/components/shared/SkeletonWrapper/SkeletonWrapper.tsx
  odd-platform-ui/src/components/shared/TestRunStatusIcon/TestRunStatusIconStyles.ts
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItem.tsx
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItemStyles.ts
  odd-platform-ui/src/components/shared/index.ts
  odd-platform-ui/src/lib/helpers.ts
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
  odd-platform-ui/src/redux/selectors/index.ts
Labels: kind: bug, scope: frontend, kind: feature

#960 README: fix formatting
  docker/README.md
Labels: kind: documentation

#969 Fix primary/sort key labels
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
Labels: kind: bug, scope: frontend

#817 #620: Make Lineage reactive
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/LineageMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/LineageMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/GroupEntityRelationRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/GroupEntityRelationRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveGroupEntityRelationRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveGroupEntityRelationRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/LineageMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/LineageRepositoryTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/LineageServiceTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/utils/RecordFactory.java
Labels: scope: backend, kind: optimization

#961 Clean-up test structure, update relations
  .gitignore
  docker/config/collector_config.yaml
  tests/config/custom.d.ts
  tests/docker/collector_setting_from_post.yaml
  tests/docker/req.json
  tests/docker/up-collector.sh
  tests/docker/up-platform.sh
  tests/envs/.env
  tests/package-lock.json
  tests/package.json
  tests/playwright.config.ts
  tests/tsconfig.json
Labels: scope: backend, scope: frontend, kind: testing

#959 Run Playwright tests in CI
  .github/workflows/release-build.yaml
  .github/workflows/run-playwright-tests.yml
  .github/workflows/run-pr-tests.yaml
  tests/playwright.config.ts
Labels: kind: testing, scope: build

#971 Install Typescript and add README for PW tests
  .github/workflows/run-playwright-tests.yml
  tests/.nvmrc
  tests/README.md
  tests/package-lock.json
  tests/package.json
  tests/playwright.config.ts
Labels: kind: documentation, kind: testing

#975 fix properties
  odd-platform-api/src/main/resources/application.yml
Labels: kind: bug

#970 Playwright add tags tests
  tests/features/owners/add-owner.spec.ts
  tests/features/tags/add-tag.spec.ts
  tests/features/tags/change-tag.spec.ts
  tests/features/tags/delete-tag.spec.ts
  tests/playwright.config.ts
  tests/ui/pages/index.ts
  tests/ui/pages/management/tags-page.ts
  tests/ui/pages/modals/add-tag-modal.ts
  tests/ui/pages/modals/delete-tag-modal.ts
  tests/ui/pages/modals/edit-tag-modal.ts
  tests/ui/pages/modals/index.ts
Labels: kind: testing

#977 Setup linter and formatter for Playwright tests
  .github/workflows/run-playwright-tests.yml
  tests/.eslintignore
  tests/.eslintrc.js
  tests/.husky/.gitignore
  tests/.husky/pre-commit
  tests/.prettierignore
  tests/.prettierrc.json
  tests/.vscode/settings.json
  tests/README.md
  tests/api/api-base.ts
  tests/api/login-service.ts
  tests/api/pilot.ts
  tests/common-utilities/array-utils.ts
  tests/common-utilities/common-utils.ts
  tests/common-utilities/error-handler.ts
  tests/common-utilities/load-document.ts
  tests/common-utilities/object-util.ts
  tests/config/configuration.ts
  tests/config/test-base.ts
  tests/docker/collector_setting_from_post.yaml
  tests/docker/req.json
  tests/features/owners/add-owner.spec.ts
  tests/features/tags/add-tag.spec.ts
  tests/features/tags/change-tag.spec.ts
  tests/features/tags/delete-tag.spec.ts
  tests/package-lock.json
  tests/package.json
  tests/playwright.config.ts
  tests/tsconfig.eslint.json
  tests/tsconfig.json
  tests/ui/elements/button.ts
  tests/ui/elements/context-menu.ts
  tests/ui/elements/custom-element.ts
  tests/ui/elements/dropdown.ts
  tests/ui/elements/file-chooser.ts
  tests/ui/elements/input-field.ts
  tests/ui/elements/list.ts
  tests/ui/elements/table.ts
  tests/ui/elements/text-box.ts
  tests/ui/pages/base-page.ts
  tests/ui/pages/index.ts
  tests/ui/pages/management/owners-page.ts
  tests/ui/pages/management/tags-page.ts
  tests/ui/pages/modals/add-owner-modal.ts
  tests/ui/pages/modals/add-tag-modal.ts
  tests/ui/pages/modals/base-modal.ts
  tests/ui/pages/modals/delete-tag-modal.ts
  tests/ui/pages/modals/edit-tag-modal.ts
  tests/ui/pages/modals/index.ts
  tests/ui/pages/shared/top-panel.ts
  tests/ui/steps/index.ts
  tests/ui/steps/login.ts
  tests/ui/utils/common-utils.ts
Labels: kind: documentation, kind: testing

#978 Gitbook activity
  docs/.gitbook/assets/image.png
  docs/.gitbook/img/oddrn.png
  docs/Architecture.md
  docs/SUMMARY.md
  docs/configuration-and-deployment/odd-platform.md
  docs/configuration-and-deployment/trylocally.md
Labels: kind: documentation

#989 Implement fetch DEG Ingestion endpoint
  gradle/libs.versions.toml
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
Labels: scope: backend, kind: feature

#993 Updating FE packages
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/vite.config.ts
Labels: kind: enhancement, scope: frontend

#1003 Extend `gradle clean` task with deleting generated API models for UI
  odd-platform-ui/build.gradle
Labels: kind: bug, kind: enhancement, scope: build

#1004 Check authentication properties
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/ODDLDAPProperties.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/logout/OAuthLogoutSuccessHandler.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/LDAPSecurityConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/FacetStateMapperImpl.java
  odd-platform-api/src/main/resources/application.yml
Labels: scope: backend

#1005 Count data entities without data source
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: kind: bug, scope: backend

#1006 Don't modify updated_at field on view count increment
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: kind: bug, scope: backend

#1007 Do not propagate collector namespace to data sources while ingesting
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceTest.java
Labels: kind: bug, scope: backend

#1008 Don't set empty parameters
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/ODDOAuth2PropertiesConverter.java
Labels: scope: backend

#1009 Update Contacts section in a README
  README.md
Labels: kind: documentation

#1011 SLA hint design updates.
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQSLAReport/OverviewDQSLAReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQSLAReport/OverviewDQSLAReportSkeleton/OverviewDQSLAReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQSLAReport/OverviewDQSLAReportStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQTestReport/OverviewDQReportSkeleton/OverviewDQReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQTestReport/OverviewDQReportSkeleton/OverviewDQReportSkeletonStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQTestReport/OverviewDQTestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportSkeleton/OverviewDataQualityReportSkeletonStyles.ts
Labels: kind: enhancement, scope: frontend

#1012 RBAC Documentation
  docs/configuration-and-deployment/odd-platform.md
Labels: kind: documentation
