Repository opendatadiscovery/odd-platform, pull requests merged in 2022-02, with the labels that each got.

#398 Bugfix/tabs prop warning
  odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
Labels: kind: bug, scope: frontend, bug

#411 Bugfix: deleted enum values are appearing in new tabs.
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsFormItem/DatasetFieldEnumsFormItem.tsx
Labels: kind: bug, scope: frontend

#410 alert status works correcttly
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
Labels: kind: bug, scope: frontend, status: accepted

#403 feature/version
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/AppInfoController.java
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarContainer.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarStyles.ts
  odd-platform-ui/src/redux/actions/appInfo.actions.ts
  odd-platform-ui/src/redux/actions/index.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/appInfo.reducer.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/appInfo.selectors.ts
  odd-platform-ui/src/redux/thunks/appInfo.thunks.ts
  odd-platform-ui/src/redux/thunks/index.ts
Labels: scope: backend, scope: frontend, kind: feature

#408 Pagination for data quality test runs
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataQualityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityTaskRunMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataQualityMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataQualityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqQueryHelper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImplTest.java
  odd-platform-api/src/test/resources/application-integration-test.yml
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunSkeletonItem/TestRunSkeletonItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistoryContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/components/shared/TestRunStatusIcon/TestRunStatusIcon.tsx
  odd-platform-ui/src/components/shared/TestRunStatusIcon/TestRunStatusIconStyles.ts
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItem.tsx
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItemStyles.ts
  odd-platform-ui/src/redux/actions/dataQualityTest.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/dataQualityTest.reducer.ts
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
  odd-platform-ui/src/redux/thunks/dataQualityTest.thunks.ts
  odd-platform-ui/src/theme/interfaces.ts
Labels: kind: enhancement, scope: backend, scope: frontend

#401 Implemented dependabot.yaml
  .github/dependabot.yml
Labels: kind: enhancement, scope: infrastructure

#420 Changed dependabot version
  .github/dependabot.yml
Labels: kind: bug, scope: infrastructure, bug

#432 fetch has alerts info
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertServiceImpl.java
Labels: kind: bug, scope: backend

#439 Updated node version to 16.4.0
  odd-platform-ui/.nvmrc
Labels: kind: enhancement, scope: frontend

#440 Enhancement/node update
  odd-platform-ui/.nvmrc
Labels: kind: enhancement, scope: frontend

#417 fixed search page styles
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Results/ResultsStyles.ts
  odd-platform-ui/src/lib/hooks.ts
Labels: kind: bug, scope: frontend, bug

#444 sort task runs in desc order
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqQueryHelper.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImplTest.java
Labels: kind: bug, scope: backend

#419 Enhancement/mui wrappers for menu&menuitem
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/shared/AppMenu/AppMenu.tsx
  odd-platform-ui/src/components/shared/AppMenu/AppMenuStyles.ts
  odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItem.tsx
  odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItemStyles.ts
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarStyles.ts
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenu.tsx
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenuStyles.ts
  odd-platform-ui/src/theme/overrides.ts
Labels: kind: enhancement, scope: frontend, status: accepted

#437 added paddings for every overview list
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/OverviewStyles.ts
Labels: kind: bug, scope: frontend, bug

#447 Sync spring versions in odd-platform-api and odd-platform-api-contract
  odd-platform-api-contract/gradle.properties
Labels: scope: backend, kind: maintenance

#451 Disable namespace update with non-unique name
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/NamespaceServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImplTest.java
Labels: kind: bug, scope: backend

#433 Enhance README file
  README.md
Labels: kind: documentation, chore

#435 Feature/copy oddrn
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
  odd-platform-ui/src/components/shared/CopyButton/CopyButton.tsx
  odd-platform-ui/src/components/shared/Icons/CopyIcon.tsx
  odd-platform-ui/src/components/shared/Icons/SuccessIcon.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
Labels: scope: frontend, kind: feature, enhancement

#456 Fill updated_at field when entity is updated
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityTaskRunRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldValueRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnerRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/RoleRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TagRepositoryImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImplTest.java
Labels: kind: bug, scope: backend, bug

#434 [Backend] - Tags Integration tests. Initial commit
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TagRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TagRepositoryImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/TagRepositoryImplTest.java
Labels: kind: enhancement, scope: backend

#455 [Backend] - Roles Integration tests. Initial commit
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/RolesRepositoryImplTest.java
Labels: kind: enhancement, scope: backend

#464 Add updated by information to alerts
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/AlertStatusEnum.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/alert/AlertDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/alert/AlertStatusEnum.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/alert/AlertTypeEnum.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/AlertMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/AlertMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_27__add_status_updated_by_to_alerts.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImplTest.java
Labels: kind: bug, kind: enhancement, scope: backend

#466 Fixed bug with alerts in "My objects" tab.
  odd-platform-ui/src/components/Alerts/Alerts.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
Labels: kind: bug, scope: frontend, bug

#450 Fixed bug with long oddrn in datasource.
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltip.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
Labels: kind: bug, scope: frontend, bug

#467 Enhancement/updating packages
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
Labels: kind: enhancement, scope: frontend

#469 Bugfix/long data quality test overflow
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
Labels: kind: bug, scope: frontend, bug

#468 Gitbook activity
  book.json
  docs/.gitbook/img/alltogether.png
  docs/.gitbook/img/architecture2.png
  docs/.gitbook/img/audience.png
  docs/Architecture.md
  docs/Data_Compliance_DS.md
  docs/Features.md
  docs/GLOSSARY.md
  docs/Overview.md
  docs/Quickstart.md
  docs/README.md
  docs/SUMMARY.md
  docs/Use_cases.md
Labels: chore

#481 Updated project deps
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
Labels: kind: enhancement, scope: frontend

#470 Add order by id to alerts and data entity
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImplTest.java
Labels: kind: bug, scope: backend, bug

#483 Upgrade Node version in the UI's build.gradle
  odd-platform-ui/build.gradle
Labels: scope: frontend, kind: maintenance

#485 Remove triage process
  .github/workflows/triage.yaml
Labels: scope: infrastructure, kind: maintenance

#471 enhancement/mui-checkbox-wrapper
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormItem/TagCreateFormItem.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormItem/TagCreateFormItemStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditFormStyles.ts
  odd-platform-ui/src/components/shared/AppCheckbox/AppCheckbox.tsx
  odd-platform-ui/src/components/shared/AppCheckbox/AppCheckboxStyles.ts
  odd-platform-ui/src/theme/overrides.ts
Labels: kind: enhancement, scope: frontend, status: accepted

#412 feature/long-json-in-metadata
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataEntityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/MetadataController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/MetadataFieldController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/MetadataBinding.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/MetadataFieldKey.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/metadata/MetadataKey.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/metadata/MetadataOrigin.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/metadata/MetadataTypeEnum.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/MetadataFieldMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/MetadataFieldMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/MetadataFieldValueMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/MetadataFieldValueMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldValueRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/MetadataFieldService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/MetadataFieldServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/MetadataService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/MetadataServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/metadata/MetadataIngestionService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/metadata/MetadataIngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/metadata/MetadataParser.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/MetadataFieldMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/MetadataFieldValueMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldValueRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/MetadataParserTest.java
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItemStyles.ts
  odd-platform-ui/src/components/shared/CopyButton/CopyButton.tsx
  odd-platform-ui/src/components/shared/Icons/DropdownIcon.tsx
Labels: scope: frontend, kind: feature, enhancement

#489 Feature/register datasources from collector mock
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/ingestion/DataSourceIngestionMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/ingestion/DataSourceIngestionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceTest.java
Labels: enhancement
