Repository opendatadiscovery/odd-platform, pull requests merged in 2022-04, with the labels that each got.

#553 Reactive jooq support
  odd-platform-api/build.gradle
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/annotation/BlockingTransactional.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/annotation/ReactiveTransactional.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/DataSourceConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/R2DBCConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/CollectorRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityTaskRunRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetStructureRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/GroupEntityRelationRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnerRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TagRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/UserOwnerMappingRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqReactiveOperations.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/metadata/MetadataIngestionServiceImpl.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/test/resources/application-integration-test.yml
Labels: kind: enhancement, scope: backend, kind: optimization

#546 enhancement/updating-packages
  odd-platform-ui/package.json
Labels: kind: enhancement, scope: frontend

#559 Fixed bug with token value equals null.
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButtonStyles.ts
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
Labels: kind: bug, scope: frontend

#563 Rollback d3-selection package.
  odd-platform-ui/.eslintrc.json
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureFieldTypeLabel/DatasetStructureFieldTypeLabel.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/redux/interfaces/datasetStructure.ts
  odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
  odd-platform-ui/src/redux/reducers/dataentityLinkedList.reducer.ts
  odd-platform-ui/src/redux/reducers/datasetStructure.reducer.ts
  odd-platform-ui/src/redux/selectors/alert.selectors.ts
  odd-platform-ui/src/redux/selectors/collectors.selectors.ts
  odd-platform-ui/src/redux/selectors/dataentityLineage.selectors.ts
  odd-platform-ui/src/redux/selectors/datasources.selectors.ts
  odd-platform-ui/src/redux/selectors/labels.selectors.ts
  odd-platform-ui/src/redux/selectors/loader-selectors.ts
  odd-platform-ui/src/redux/selectors/namespace.selectors.ts
  odd-platform-ui/src/redux/selectors/owners.selectors.ts
  odd-platform-ui/src/redux/thunks/base.thunk.ts
Labels: kind: bug, scope: frontend

#564 Gitbook activity
  docs/.gitbook/img/alerting.gif
  docs/.gitbook/img/dqtest.gif
  docs/.gitbook/img/lineage.gif
  docs/.gitbook/img/logging.gif
  docs/.gitbook/img/storage.gif
  docs/.gitbook/img/tagging.gif
  docs/Features.md
Labels: kind: documentation

#557 Implement sonarcloud scans
  .github/workflows/main.yaml
  .github/workflows/sonar-backend.yaml
  .github/workflows/sonar-frontend.yaml
  odd-platform-api/build.gradle
  odd-platform-ui/build.gradle
Labels: kind: feature, scope: infrastructure, kind: maintenance, status: accepted

#567 Add mapstruct configuration
  odd-platform-api/build.gradle
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/MapperConfig.java
Labels: kind: enhancement, scope: backend

#576 Uplift Spring Boot version 2.5.0 -> 2.6.2
  odd-platform-api/build.gradle
  odd-platform-api/gradle.properties
Labels: scope: backend, kind: maintenance

#580 Fixed bug with checkbox.
  odd-platform-ui/src/components/shared/AppCheckbox/AppCheckbox.tsx
Labels: kind: bug, scope: frontend

#577 Decomposed autocompletes
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/MetadataItem/MetadataItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadata.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipFormOwnerAutocomplete/OwnershipFormOwnerAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipFormRoleAutocomplete/OwnershipFormRoleAutocomplete.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItem.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocompleteContainer.ts
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocompleteStyles.ts
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemStyles.ts
  odd-platform-ui/src/components/shared/AppButton/AppButtonStyles.ts
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
  odd-platform-ui/src/lib/helpers.ts
Labels: kind: enhancement, scope: frontend

#582 Fix recursive infinite loop in the Alerts API
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
Labels: kind: bug, scope: backend

#578 Gitbook activity
  docs/.gitbook/img/architecture_collector.png
  docs/Adapters.md
  docs/Architecture.md
  docs/Features.md
  docs/SUMMARY.md
Labels: kind: documentation

#590 Set up codeowners file
  .github/CODEOWNERS
Labels: kind: maintenance
