Repository opendatadiscovery/odd-platform, pull requests merged in 2022-12, with the labels that each got.

#1139 Example of using the workerId to mark test entities and make them unique
  tests/features/owners/add-owner.spec.ts
  tests/hooks/global-setup.ts
  tests/playwright.config.ts
Labels: kind: testing

#1120 Added tests for searching in data-entity and added new data-entities
  tests/.eslintignore
  tests/.prettierignore
  tests/docker/docker-compose.yaml
  tests/docker/injector/datasources/datasources.json
  tests/docker/injector/samples/01_etl_aqa.json
  tests/docker/injector/samples/02_oracle_fl_aqa.json
  tests/docker/injector/samples/03_oracle_ingestion_aqa.json
  tests/docker/injector/samples/04_airflow_ingestion_aqa.json
  tests/features/filters/filters.spec.ts
  tests/features/search/search_in_data_entity.spec.ts
  tests/package-lock.json
  tests/package.json
  tests/ui/elements/list.ts
  tests/ui/pages/catalog/catalog-page.ts
  tests/ui/pages/data_entity/overview.page.ts
  tests/ui/pages/data_entity/structure.ts
  tests/ui/pages/index.ts
  tests/ui/pages/main/main-page.ts
Labels: kind: testing

#1155 FE packages updated
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
Labels: kind: enhancement, scope: frontend

#1157 Paginate Alert's API for Data Entity
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataEntityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAlertRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAlertRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/AlertIngestionTest.java
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/Alerts/Alerts.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlerts.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsTabs/DataEntityDetailsTabs.tsx
  odd-platform-ui/src/lib/constants.ts
  odd-platform-ui/src/redux/actions/alert.actions.ts
  odd-platform-ui/src/redux/interfaces/common.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/selectors/alert.selectors.ts
  odd-platform-ui/src/redux/slices/alerts.slice.ts
  odd-platform-ui/src/redux/thunks/alerts.thunks.ts
Labels: kind: feature

#1164 Fix bug with alert ingestion
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAlertRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/alert/AlertActionResolverImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/AlertIngestionTest.java
Labels: kind: bug

#1146 Fix flaky tests
  .gitignore
  tests/features/filters/filters.spec.ts
  tests/features/search/search.spec.ts
  tests/features/search/search_in_data_entity.spec.ts
  tests/features/tags/add-tag.spec.ts
  tests/features/tags/change-tag.spec.ts
  tests/package.json
  tests/playwright.config.ts
  tests/ui/elements/list.ts
  tests/ui/pages/catalog/catalog-page.ts
  tests/ui/pages/data_entity/overview.page.ts
  tests/ui/pages/management/tags-page.ts
  tests/ui/pages/modals/add-tag-modal.ts
Labels: kind: bug

#1178 Housekeeping on empty partitions of Activity and Message tables
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/alert/AlertTypeEnum.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/HousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/HousekeepingJobManager.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/job/ActivityEmptyPartitionsHousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/job/AlertHousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/job/EmptyPartitionsHousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/job/HousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/job/MessageEmptyPartitionsHousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/job/SearchFacetsHousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/partition/manager/AbstractPartitionManager.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/partition/manager/ActivityTablePartitionManager.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/partition/manager/MessageTablePartitionManager.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/partition/service/PartitionService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/partition/service/PartitionServiceImpl.java
Labels: kind: feature

#1179 Retry sending messages to MessageProviders
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/config/DataCollaborationProperties.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/job/DataCollaborationMessageSenderJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/repository/DataCollaborationRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/repository/DataCollaborationRepositoryImpl.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/main/resources/db/migration/V0_0_63__add_try_count_to_message.sql
Labels: kind: feature

#1159 Lineage state in query params
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataEntityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/LineageServiceTest.java
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsTabs/DataEntityDetailsTabs.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageControls/LineageControls.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/LineageGraph.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Info/GroupedEntitiesListModal/GroupedEntitiesListModal.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Info/Info.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/LoadMoreButton/LoadMoreButton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Node.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/NodeTitle/NodeTitle.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/ZoomableLineage.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/LineageContext/LineageContext.ts
  odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/LineageContext/LineageProvider.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/constants.ts
  odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/generateNodeSize.ts
  odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/interfaces.ts
  odd-platform-ui/src/lib/hooks/index.ts
  odd-platform-ui/src/lib/hooks/useAppPaths.ts
  odd-platform-ui/src/lib/hooks/useQueryParams.ts
  odd-platform-ui/src/redux/interfaces/dataentityLineage.ts
  odd-platform-ui/src/redux/slices/dataEntityLineage/dataEntityLineage.slice.ts
  odd-platform-ui/src/redux/thunks/dataentityLineage.thunks.ts
Labels: scope: backend, scope: frontend, kind: feature

#1184 Bugfix: Lineage button "Main" work incorrectly
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/NotificationSettings/AlertTypeRange/AlertTypeRange.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/LineageGraph.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Classes/Classes.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/HiddenDependencies/HiddenDependencies.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Info/Info.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Node.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/NodeTitle/NodeTitle.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/ZoomableLineage.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/constants.ts
  odd-platform-ui/src/lib/hooks/useQueryParams.ts
  odd-platform-ui/src/redux/selectors/dataentityLineage.selectors.ts
Labels: kind: bug, scope: frontend

#1165 Cleanup inputs and close modal windows tests
  tests/features/owners/add-owner.spec.ts
  tests/features/search/search.spec.ts
  tests/features/tags/add-tag.spec.ts
  tests/ui/elements/custom-element.ts
  tests/ui/pages/catalog/catalog.page.ts
  tests/ui/pages/modals/add-owner-modal.ts
  tests/ui/pages/modals/add-tag-modal.ts
Labels: kind: testing

#1170 Worflow triggering rules
  .github/workflows/run-pr-tests.yaml
  tests/README.md
Labels: kind: documentation

#1193 Fix concurrent modification error in tests and run tests in parallel (4 threads)
  tests/features/activity/activity.spec.ts
  tests/features/search/search_in_data_entity.spec.ts
  tests/playwright.config.ts
Labels: kind: bug
