Repository opendatadiscovery/odd-platform, pull requests merged in 2022-08, with the labels that each got.

#882 Remove puller support
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
Labels: kind: enhancement, scope: backend

#854 Long data source names are not being shown properly in the search filters' UI #813
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchFilters/TermSearchFilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/shared/Activity/ActivityFilterItems/SingleFilter/SingleFilter.tsx
  odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItem.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelect.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelectStyles.ts
Labels: kind: bug, scope: frontend

#834 Virtual scrolling disallows from searching content on the structure page #335
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTable.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableContainer.tsx
Labels: kind: bug, scope: frontend

#892 Exclude non updatable fields from update many query
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractSoftDeleteCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTermRepositoryImpl.java
Labels: kind: bug, scope: backend

#893 Fix wrong dataset field enums count
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepositoryImpl.java
Labels: kind: bug, scope: backend

#876 Migrate DataSet structure section to Redux toolkit #847
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsEditFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItemContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTable.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/lib/constants.ts
  odd-platform-ui/src/lib/hooks/useAppParams.ts
  odd-platform-ui/src/redux/actions/datasetStructure.actions.ts
  odd-platform-ui/src/redux/interfaces/datasetStructure.ts
  odd-platform-ui/src/redux/reducers/datasetStructure.reducer.ts
  odd-platform-ui/src/redux/reducers/datasetStructure.slice.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/selectors/datasetStructure.selectors.ts
  odd-platform-ui/src/redux/thunks/datasetStructure.thunks.ts
Labels: kind: enhancement, scope: frontend

#889 Tests overview ui fixes
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/lib/constants.ts
Labels: kind: bug, scope: frontend

#897 Fix blocking repository update many query
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityTaskRunRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldValueRepositoryImpl.java
Labels: kind: bug, scope: backend

#859 Migrate Profile section to Redux toolkit #846
  odd-platform-ui/src/components/App.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialogContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescriptionContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneralContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStatsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTags.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipFormContainer.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Overview/IdentityForm/Identity.tsx
  odd-platform-ui/src/components/Overview/IdentityForm/IdentityContainer.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/Overview/OverviewStyles.ts
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewContainer.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarContainer.tsx
  odd-platform-ui/src/components/shared/Icons/index.ts
  odd-platform-ui/src/components/shared/index.ts
  odd-platform-ui/src/redux/actions/dataentity.actions.ts
  odd-platform-ui/src/redux/actions/profile.actions.ts
  odd-platform-ui/src/redux/actions/terms.actions.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/reducers/profile.reducer.ts
  odd-platform-ui/src/redux/reducers/profile.slice.ts
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/selectors/index.ts
  odd-platform-ui/src/redux/selectors/mainContentLoader.selectors.ts
  odd-platform-ui/src/redux/selectors/owners.selectors.ts
  odd-platform-ui/src/redux/selectors/profile.selectors.ts
  odd-platform-ui/src/redux/selectors/tags.selectors.ts
  odd-platform-ui/src/redux/selectors/termLinkedList.selectors.ts
  odd-platform-ui/src/redux/selectors/terms.selectors.ts
  odd-platform-ui/src/redux/thunks/dataentities.thunks.ts
  odd-platform-ui/src/redux/thunks/profile.thunks.ts
Labels: kind: enhancement, scope: frontend

#899 New design for my/upstream/downstream/popular entities in main overview page
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityList.tsx
  odd-platform-ui/src/components/Overview/DataEntityList/DataEntityListStyles.ts
  odd-platform-ui/src/components/Overview/OverviewStyles.ts
Labels: kind: enhancement, scope: frontend, kind: feature

#903 assignWith update
  odd-platform-ui/src/lib/redux/helpers.ts
Labels: scope: frontend

#875 Dataset structure redesign #845
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureKeyFieldLabel/DatasetStructureKeyFieldLabel.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureKeyFieldLabel/DatasetStructureKeyFieldLabelStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldCollapsedDescription/DatasetFieldCollapsedDescription.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldStats/DatasetFieldStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldStats/DatsetFieldStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldTypeLabel/DatasetFieldTypeLabel.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldTypeLabel/DatasetFieldTypeLabelStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTable.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTableStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTypeCountLabelList/DatasetStructureTypeCountLabel/DatasetStructureTypeCountLabel.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTypeCountLabelList/DatasetStructureTypeCountLabel/DatasetStructureTypeCountLabelStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTypeCountLabelList/DatasetStructureTypeCountLabelList.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/shared/AppInput/AppInputStyles.ts
  odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItem.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelect.tsx
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltip.tsx
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltipStyles.tsx
  odd-platform-ui/src/components/shared/Icons/GraphIcon.tsx
  odd-platform-ui/src/components/shared/Icons/InformationIcon.tsx
  odd-platform-ui/src/components/shared/Icons/index.ts
  odd-platform-ui/src/components/shared/index.ts
  odd-platform-ui/src/redux/interfaces/datasetStructure.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/datasetStructure.slice.ts
  odd-platform-ui/src/redux/selectors/datasetStructure.selectors.ts
  odd-platform-ui/src/theme/palette.ts
Labels: kind: bug, kind: enhancement, scope: frontend

#911 Data entities Search to redux toolkit
  odd-platform-ui/src/components/Activity/ActivityResults/ActivityResults.tsx
  odd-platform-ui/src/components/App.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/TopTagsList/TopTagsList.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItem.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocompleteContainer.ts
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemContainer.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SelectedFilterOption/SelectedFilterOption.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItemContainer.tsx
  odd-platform-ui/src/components/Search/Filters/Filters.tsx
  odd-platform-ui/src/components/Search/Filters/FiltersContainer.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Results/ResultsContainer.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeleton/SearchResultsSkeleton.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeleton/SearchResultsSkeletonStyles.ts
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeletonItem/SearchResultsSkeletonItem.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsTabs/SearchResultsTabs.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsTabs/SearchTabsSkeleton/SearchTabsSkeleton.tsx
  odd-platform-ui/src/components/Search/Search.tsx
  odd-platform-ui/src/components/Search/SearchContainer.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermLinkedItemsList/LinkedItemsList.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchFilters/TermSearchFilterItem/MultipleFilterItem/MultipleFilterItem.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchFilters/TermSearchFilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabLabel/AppTabLabel.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearch.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchContainer.tsx
  odd-platform-ui/src/components/shared/index.ts
  odd-platform-ui/src/lib/hooks/useAppParams.ts
  odd-platform-ui/src/redux/actions/dataentitySearch.actions.ts
  odd-platform-ui/src/redux/interfaces/common.ts
  odd-platform-ui/src/redux/interfaces/dataEntitySearch.ts
  odd-platform-ui/src/redux/interfaces/index.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/interfaces/termSearch.ts
  odd-platform-ui/src/redux/reducers/dataEntitySearch.slice.ts
  odd-platform-ui/src/redux/reducers/dataentitiesSearch.reducer.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
  odd-platform-ui/src/redux/thunks/dataentitiesSearch.thunks.ts
Labels: kind: enhancement, scope: frontend

#920 Docs/implemented_adapters
  README.md
  images/bigquery-logo.png
  images/tableau-logo.jpg
  images/tableau-logo.png
Labels: kind: documentation

#922 Gitbook activity
  docker/config/collector_config.yaml
  docs/.gitbook/img/activity.gif
  docs/.gitbook/img/groups.gif
  docs/.gitbook/img/report.png
  docs/.gitbook/img/terms.gif
  docs/.gitbook/img/trylocally1.gif
  docs/.gitbook/img/trylocally2.gif
  docs/Architecture.md
  docs/Features.md
  docs/Quickstart.md
  docs/SUMMARY.md
  docs/collector.md
  docs/configuration.md
  docs/deployment.md
  docs/platform.md
  docs/quick_start.md
  docs/trylocally.md
Labels: kind: documentation

#926 fix pagination
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractCRUDRepository.java
Labels: kind: bug, scope: backend

#931 FE Bugfixes
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/Activity/ActivityResults/ActivityResults.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupStats/OverviewEntityGroupStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/shared/AppDateRangePicker/AppDateRangePicker.tsx
  odd-platform-ui/src/components/shared/AppDateRangePicker/AppDateRangePickerFooter/AppDateRangePickerFooter.tsx
  odd-platform-ui/src/components/shared/AppDateRangePicker/overrides.css
  odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItemStyles.ts
  odd-platform-ui/src/components/shared/AppSelect/AppSelect.tsx
  odd-platform-ui/src/components/shared/Autocomplete/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/slices/dataEntityRuns.slice.ts
  odd-platform-ui/src/redux/thunks/dataentities.thunks.ts
Labels: kind: bug, scope: frontend
