Repository opendatadiscovery/odd-platform, pull requests merged in 2022-06, with the labels that each got.

#706 Cast Integer to Long
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
Labels: kind: bug, scope: backend

#692 Refactor Enums to reactive approach
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DatasetFieldController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/EnumValueMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/EnumValueMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractSoftDeleteCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveEnumValueRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveEnumValueRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/EnumValueServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_40__add_deleted_at_enum_value.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/EnumValueMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/EnumValueServiceTest.java
Labels: kind: enhancement, scope: backend

#705 Gitbook activity
  docker/config/collector_config.yaml
  docker/demo.yaml
  docs/.gitbook/img/sdlc.png
  docs/Quickstart.md
  docs/README.md
Labels: kind: documentation

#712 Support multiple session providers
  gradle/libs.versions.toml
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/filter/IngestionDataSourceFilter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/session/JooqSessionRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/session/PostgreSQLSessionHousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/session/PostgreSQLSessionHousekeepingJobHandler.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/session/SessionConstants.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/SessionConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/main/resources/db/migration/V0_0_41__add_session_tables.sql
Labels: scope: backend, kind: feature

#718 Data Entity's overview test report shows stats of test runs instead of tests
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataQualityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/ingestion/IngestionTaskRun.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataQualityMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataQualityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/OffsetDateTimeMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_42__additional_indexes_to_dq_test_tables.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImplTest.java
Labels: kind: bug, kind: enhancement, scope: backend

#700 [Backend] - DatasetField refactoring.
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetFieldRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveSearchEntrypointRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveSearchEntrypointRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetFieldRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/utils/JSONTestUtils.java
Labels: scope: backend, kind: optimization

#724 Support DataTransformerRuns in the platform
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataEntityRunController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataQualityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityRunMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataQualityMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRunRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRunRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityRunService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityRunServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataEntityRunRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveDatasetFieldRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/utils/DataEntityTaskRunPojoEndTimeComparator.java
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunItem/TestRunItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunStatusReasonModal/TestRunStatusReasonModal.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestItem/TestItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/components/shared/TestRunStatusIcon/TestRunStatusIcon.tsx
  odd-platform-ui/src/components/shared/TestRunStatusIcon/TestRunStatusIconStyles.ts
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItem.tsx
  odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItemStyles.ts
  odd-platform-ui/src/redux/actions/dataQualityTest.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/dataQualityTest.reducer.ts
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/thunks/dataQualityTest.thunks.ts
  odd-platform-ui/src/theme/interfaces.ts
Labels: scope: backend, scope: frontend, kind: feature

#729 Fix arithmetic division by zero in the DatasetTestReport API
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataQualityMapper.java
  odd-platform-api/src/main/resources/application.yml
Labels: kind: bug, scope: backend

#730 Actualize Integration section in the main README
  README.md
  images/amazon-athena-logo.png
  images/apache-hive-logo.jpg
  images/cassandra.png
  images/clickhouse-logo.jpg
  images/clickhouse-logo.png
  images/dynamodb-logo.jpg
  images/dynamodb-logo.png
  images/elasticsearch.png
  images/feast.png
  images/hive.png
  images/kinesis.png
  images/microsoft-odbc-logo.jpg
  images/mongodb.png
  images/mssql-server-logo.jpg
  images/mssql.png
  images/neo4j.png
  images/odbc.png
  images/quicksight.png
  images/s3.png
  images/sagemaker-featurestore.png
  images/sagemaker.png
  images/sqs.png
  images/tarantool.png
Labels: kind: documentation, kind: enhancement

#740 Create hollow entities on DQT relation ingestion payload
  docker/injector/inject.py
  docker/injector/samples/ge_ingestion.json
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_43__additional_keys_to_dq_test_relation.sql
Labels: kind: bug, scope: backend

#716 Add/remove data entity with DEG relations API
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataEntityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/SearchController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveGroupEntityRelationRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveGroupEntityRelationRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/SearchService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/SearchServiceImpl.java
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/EntitiesSuggestionsAutoocomplete/EntitiesSuggestionsAutocompleteContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/NamespaceAutocomplete/NamespaceAutocompleteContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/AddDataEntityToGroupForm/AddDataEntityToGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/GroupItem/GroupItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/GroupItem/GroupItemStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/OverviewGroups.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/OverviewGroupsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadata.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocompleteContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/NamespaceAutocomplete/NamespaceAutocompleteContainer.tsx
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/components/Management/NamespaceList/EditableNamespaceItem/EditableNamespaceItem.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceForm.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceFormContainer.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListContainer.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/NamespaceAutocomplete/NamespaceAutocompleteContainer.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx
  odd-platform-ui/src/components/shared/Autocomplete/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearch.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchContainer.tsx
  odd-platform-ui/src/redux/actions/dataentity.actions.ts
  odd-platform-ui/src/redux/actions/dataentitySearch.actions.ts
  odd-platform-ui/src/redux/actions/namespace.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/dataEntityLineage/dataEntityLineageHelpers.ts
  odd-platform-ui/src/redux/reducers/dataEntitySearch.slice.ts
  odd-platform-ui/src/redux/reducers/dataentitiesSearch.reducer.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/reducers/namespace.reducer.ts
  odd-platform-ui/src/redux/reducers/namespace.slice.ts
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
  odd-platform-ui/src/redux/selectors/namespace.selectors.ts
  odd-platform-ui/src/redux/thunks/dataentities.thunks.ts
  odd-platform-ui/src/redux/thunks/dataentitiesSearch.thunks.ts
  odd-platform-ui/src/redux/thunks/namespace.thunks.ts
Labels: kind: enhancement, scope: backend, scope: frontend

#743 Forbid to delete entity from datasource's deg
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/GroupItem/GroupItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupStats/OverviewEntityGroupStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupStats/OverviewEntityGroupStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStats.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphCrossLink/AppGraphCrossLinkStyles.ts
  odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLinkStyles.ts
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
Labels: kind: bug, scope: backend, scope: frontend

#747 Use r2dbc database client
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqReactiveOperations.java
Labels: kind: enhancement, scope: backend

#758 Alerts for data transformers
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/alert/AlertTypeEnum.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocator.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-specification/components.yaml
Labels: kind: enhancement, scope: backend

#760 Fix DataTransformer history selector
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
Labels: kind: bug, scope: frontend

#759 Migrate Labels section to Redux toolkit (Issue #748)
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocompleteContainer.tsx
  odd-platform-ui/src/components/Management/LabelsList/EditableLabelItem/EditableLabelItem.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateFormContainer.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditFormContainer.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsListContainer.tsx
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/redux/actions/labels.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/reducers/labels.reducer.ts
  odd-platform-ui/src/redux/reducers/labels.slice.ts
  odd-platform-ui/src/redux/selectors/labels.selectors.ts
  odd-platform-ui/src/redux/thunks/labels.thunks.ts
Labels: kind: enhancement, scope: frontend

#761 migrate tags to redux toolkit
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormContainer.tsx
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItem.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormContainer.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditFormContainer.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsListContainer.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/redux/actions/tags.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/tags.reducer.ts
  odd-platform-ui/src/redux/reducers/tags.slice.ts
  odd-platform-ui/src/redux/selectors/tags.selectors.ts
  odd-platform-ui/src/redux/thunks/tags.thunks.ts
Labels: kind: enhancement, scope: frontend

#764 Fix tags 745
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/redux/reducers/index.ts
Labels: kind: bug

#763 migrate datasource to redux toolkit
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceFormContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemToken/DataSourceItemToken.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemToken/DataSourceItemTokenContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListContainer.tsx
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/components/Search/Filters/Filters.tsx
  odd-platform-ui/src/components/Search/Filters/FiltersContainer.tsx
  odd-platform-ui/src/redux/actions/datasource.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/datasources.reducer.ts
  odd-platform-ui/src/redux/reducers/datasources.slice.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/datasources.selectors.ts
  odd-platform-ui/src/redux/thunks/datasources.thunks.ts
Labels: kind: enhancement, scope: frontend

#765 migrate collectors to redux toolkit
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorFormContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItem.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemToken.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemTokenContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsList.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsListContainer.tsx
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/redux/actions/collector.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/collectors.reducer.ts
  odd-platform-ui/src/redux/reducers/collectors.slice.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/collectors.selectors.ts
  odd-platform-ui/src/redux/thunks/collectors.thunks.ts
Labels: kind: enhancement, scope: frontend

#771 migrate Alerts to redux-toolkit
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/Alerts/Alerts.tsx
  odd-platform-ui/src/components/Alerts/AlertsContainer.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsListContainer.tsx
  odd-platform-ui/src/components/App.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlerts.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/components/Management/ManagementContainer.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabLabel/AppTabLabelStyles.ts
  odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
  odd-platform-ui/src/lib/hooks.ts
  odd-platform-ui/src/lib/interfaces.ts
  odd-platform-ui/src/lib/paths.ts
  odd-platform-ui/src/redux/actions/alert.actions.ts
  odd-platform-ui/src/redux/interfaces/alert.ts
  odd-platform-ui/src/redux/interfaces/index.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/interfaces/terms.ts
  odd-platform-ui/src/redux/reducers/alerts.reducer.ts
  odd-platform-ui/src/redux/reducers/alerts.slice.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/alert.selectors.ts
  odd-platform-ui/src/redux/selectors/mainContentLoader.selectors.ts
  odd-platform-ui/src/redux/thunks/alerts.thunks.ts
  odd-platform-ui/src/redux/thunks/namespace.thunks.ts
Labels: kind: enhancement, scope: frontend

#773 SLA MVP
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/session/JooqSessionRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/SessionConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataQualityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/SLA.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/TestStatusWithSeverityDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/ingestion/IngestionTaskRun.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityTaskRunMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityTaskRunRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRunRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqQueryHelper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataQualityServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/metric/extractors/TaskRunMetricExtractor.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/sla/SLACalculator.java
  odd-platform-api/src/main/resources/db/migration/V0_0_44__dataqatest_severity.sql
  odd-platform-api/src/main/resources/db/migration/V0_0_45__last_runs_table.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataEntityRunRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/sla/SLACalculatorTest.java
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemContainer.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/lib/hooks.ts
  odd-platform-ui/src/redux/actions/dataQualityTest.actions.ts
  odd-platform-ui/src/redux/thunks/dataQualityTest.thunks.ts
Labels: scope: backend, scope: frontend, kind: feature

#762 Support primary and sort keys flags
  gradle/libs.versions.toml
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapperImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_46__primary_and_sort_key_for_dataset_field.sql
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureKeyFieldLabel/DatasetStructureKeyFieldLabel.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureKeyFieldLabel/DatasetStructureKeyFieldLabelStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/shared/AppPopover/AppPopover.tsx
  odd-platform-ui/src/components/shared/TruncatedLabel/TruncatedLabel.tsx
  odd-platform-ui/src/components/shared/TruncatedLabel/TruncatedLabelMenu/TruncatedLabelMenu.tsx
  odd-platform-ui/src/components/shared/TruncatedLabel/TruncatedLabelStyles.ts
  odd-platform-ui/src/theme/interfaces.ts
  odd-platform-ui/src/theme/palette.ts
Labels: scope: backend, scope: frontend, kind: feature
