Repository opendatadiscovery/odd-platform, pull requests merged in 2022-05, with the labels that each got.

#600 Enhance local demo and local demo documentation
  dev/.env
  dev/requests/data/dbt.json
  dev/requests/data/glue.json
  dev/requests/data/great_exp.json
  dev/requests/data/tableau.json
  dev/requests/ds/dbt.json
  dev/requests/ds/glue.json
  dev/requests/ds/great_exp.json
  dev/requests/ds/tableau.json
  dev/requests/ingest.sh
  docker/.env
  docker/README.md
  docker/config/collector_config.yaml
  docker/config/dump.sql
  docker/demo.yaml
  docker/examples/README.md
  docker/examples/config/alert_rules.yaml
  docker/examples/config/alertmanager.yaml
  docker/examples/config/otel_collector.yaml
  docker/examples/config/prometheus.yaml
  docker/examples/ldap.yaml
  docker/examples/oauth2.yaml
  docker/injector/datasources/datasources.json
  docker/injector/inject.py
  docker/injector/samples/airflow_ingestion.json
  docker/injector/samples/bookshop_datalake_ingestion.json
  docker/injector/samples/bookshop_tr_ingestion.json
  docker/injector/samples/etl_ingestion.json
  docker/injector/samples/ge_ingestion.json
  docker/injector/samples/kafka_del_ingestion.json
  docker/injector/samples/kinesis_consumer_ingestion.json
  docker/injector/samples/kinesis_ingestion.json
  docker/injector/samples/s3_ingestion.json
  docker/injector/samples/snowflake_ingestion.json
  docker/injector/start.sh
Labels: kind: documentation, kind: maintenance, scope: documentation

#610 Add Privacy Policy
  PRIVACY_POLICY.txt
Labels: kind: chore

#626 Add custom OAuth login page
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/OAuthSecurityConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/ResourceProviderWebFilter.java
  odd-platform-api/src/main/resources/static/img/cognito.png
  odd-platform-api/src/main/resources/static/img/github.png
  odd-platform-api/src/main/resources/static/img/google.png
  odd-platform-api/src/main/resources/templates/oauth2_login.html
Labels: kind: enhancement, scope: backend, scope: frontend, kind: feature

#629 Fix view count field is not being updated
  odd-platform-api/src/main/resources/db/migration/V0_0_37__update_view_count.sql
Labels: kind: bug, scope: backend

#635 Fixed bug with search suggestions loader.
  odd-platform-ui/src/components/Terms/TermDetails/TermLinkedItemsList/LinkedItemsList.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermMainSearch/TermMainSearch.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermMainSearch/TermMainSearchContainer.tsx
  odd-platform-ui/src/lib/helpers.ts
  odd-platform-ui/src/redux/selectors/termSearch.selectors.ts
Labels: kind: bug, kind: enhancement, scope: frontend

#636 Fix missed tags and owners after term update
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/term/TermServiceImpl.java
Labels: kind: bug, scope: backend

#637 Fix collector_config.yaml syntax in demo README file
  docker/config/collector_config.yaml
Labels: kind: bug, kind: documentation

#644 Show term definition in term list at data entity's page
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTerms/AddTermsForm/TermsAutocomplete/TermsAutocomplete.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx
  odd-platform-ui/src/components/shared/AppTextField/AppTextField.tsx
  odd-platform-ui/src/components/shared/TermItem/TermItem.tsx
  odd-platform-ui/src/components/shared/TermItem/TermItemStyles.ts
Labels: kind: enhancement, scope: frontend

#640 Refactor label logic to the reactive approach
  .github/workflows/run-tests.yaml
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/LabelController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/LabelMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/LabelMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveSearchEntrypointRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveSearchEntrypointRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AbstractCRUDService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LabelService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LabelServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ReactiveLabelService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ReactiveLabelServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_38__add_deleted_at_to_label.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveLabelRepositoryImplTest.java
Labels: kind: enhancement, scope: backend

#648 Enhance build jobs
  .github/workflows/release-build.yaml
  .github/workflows/run-tests.yaml
  odd-platform-ui/package.json
Labels: scope: infrastructure, kind: maintenance

#659 Link alert with dataset instead of data quality test
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityTestRelationRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityTestRelationRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
Labels: kind: bug, scope: backend

#658 Enhance build jobs
  .github/workflows/main-build.yaml
  .github/workflows/release-build.yaml
  .github/workflows/run-pr-tests.yaml
  .github/workflows/sonar-backend.yaml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  odd-platform-api/build.gradle
  odd-platform-ui/build.gradle
Labels: kind: enhancement, scope: infrastructure

#657 Dependabot config
  .github/dependabot.yml
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
Labels: kind: enhancement, scope: frontend, scope: infrastructure

#675 Fix dependabot config typo
  .github/dependabot.yml
Labels: kind: bug, scope: frontend, scope: infrastructure

#676 Design updates
  .github/dependabot.yml
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItem.tsx
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItemStyles.ts
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
  odd-platform-ui/src/components/shared/AppTooltip/AppTooltip.tsx
  odd-platform-ui/src/components/shared/NumberFormatted/NumberFormatted.tsx
Labels: kind: bug, kind: enhancement, scope: frontend

#684 Uplift R2DBC SPI
  odd-platform-api-contract/gradle.properties
  odd-platform-api/build.gradle
  odd-platform-api/gradle.properties
Labels: kind: enhancement, scope: backend, kind: maintenance

#685 Add concurrency to GH Actions jobs and workflows
  .github/workflows/main-build.yaml
  .github/workflows/release-build.yaml
Labels: kind: enhancement, scope: infrastructure, kind: maintenance

#686 Remove starters from api module
  odd-platform-api-contract/build.gradle
  odd-platform-api-contract/gradle.properties
Labels: kind: enhancement, scope: backend

#693 Enhance READMEs
  README.md
  docker/README.md
Labels: kind: documentation, kind: enhancement, scope: documentation

#699 Migration from CRA to Vite
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/ResourceProviderWebFilter.java
  odd-platform-ui/.env
  odd-platform-ui/.eslintignore
  odd-platform-ui/.eslintrc.json
  odd-platform-ui/.prettierrc
  odd-platform-ui/babel.config.js
  odd-platform-ui/build.gradle
  odd-platform-ui/index.html
  odd-platform-ui/jest.config.js
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/public/index.html
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunStatusReasonModal/TestRunStatusReasonModal.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermDetails.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermDetailsStyles.ts
  odd-platform-ui/src/components/shared/EntityClassItem/__tests__/EntityClassItem.test.tsx
  odd-platform-ui/src/components/shared/EntityTypeItem/EntityTypeItem.tsx
  odd-platform-ui/src/index.tsx
  odd-platform-ui/src/lib/constants.ts
  odd-platform-ui/src/react-app-env.d.ts
  odd-platform-ui/src/serviceWorker.ts
  odd-platform-ui/src/setupTests.ts
  odd-platform-ui/src/vite-env.d.ts
  odd-platform-ui/tsconfig.json
  odd-platform-ui/vite.config.ts
Labels: kind: enhancement, scope: frontend, scope: infrastructure, kind: optimization
