Repository opendatadiscovery/odd-platform, pull requests merged in 2022-10, with the labels that each got.

#1018 Add more verbose exception message to the resolveType operation in the Ingestion API getByDegOddrn endpoint
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
Labels: kind: bug

#1021 Introduce housekeeping for resolved alerts and outdated searches
  gradle/libs.versions.toml
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/ODDPlatformConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/HousekeepingJob.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/config/HousekeepingConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/config/HousekeepingTTLProperties.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/FacetStateMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationSubscriberStarter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/SearchFacetRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveSearchFacetRepositoryImpl.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/main/resources/db/migration/V0_0_52__introduce_housekeeping.sql
  odd-platform-api/src/test/resources/application-integration-test.yml
Labels: kind: enhancement, scope: backend, kind: feature

#1023 Bugfix: avoid to creating new search by modifying search query
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/FacetStateDto.java
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/Overview/Overview.tsx
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Search.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermMainSearch/TermMainSearch.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermMainSearch/TermMainSearchStyles.ts
  odd-platform-ui/src/components/Terms/TermSearch/TermSearch.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchInput/TermSearchInput.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchResults/TermSearchResults.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchResults/TermSearchResultsStyles.ts
  odd-platform-ui/src/components/shared/AppInput/AppInput.tsx
  odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx
  odd-platform-ui/src/components/shared/AutocompleteSuggestion/AutocompleteSuggestion.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearch.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearchStyles.ts
  odd-platform-ui/src/components/shared/MainSearchInput/MainSearchInput.tsx
  odd-platform-ui/src/components/shared/index.ts
  odd-platform-ui/src/redux/selectors/termSearch.selectors.ts
  odd-platform-ui/src/redux/slices/dataEntitySearch.slice.ts
  odd-platform-ui/src/redux/slices/termSearch.slice.ts
Labels: kind: bug, scope: frontend

#1025 Fix several bugs in Ingestion API
  docker/injector/samples/bookshop_datalake_ingestion.json
  docker/injector/samples/s3_ingestion.json
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/DatasetStructureIngestionRequestProcessor.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/DatasetIngestionTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/utils/IngestionModelGenerator.java
Labels: kind: bug, scope: backend

#1027 Owner name displayed firstly in toolbar.
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbarStyles.ts
Labels: scope: frontend, kind: feature

#1030 Update integrations list
  README.md
  images/cube-logo.svg
  images/presto-logo.svg
  images/trino-og.png
  images/vertica-logo.svg
Labels: kind: documentation

#1036 Filter entities without penultimate versions in AlertLocator
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
Labels: kind: bug, scope: backend

#1034 Update integration list
  README.md
  images/mariadb.svg
  images/superset.svg
Labels: kind: documentation

#1039 Metadata and description bugfix
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
Labels: kind: bug, scope: frontend

#1040 Metadata bugfix
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
Labels: kind: bug, scope: frontend

#1041 Creating metadata bugfix
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
Labels: kind: bug, scope: frontend

#1043 Filter by DEG's and tab showing DEGs in which an entity is
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/FacetType.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/FacetStateMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/SearchFacetRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/SearchFacetRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/FTSConstants.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/SearchServiceImpl.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertsSkeleton/DataEntityAlertsSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/LinkedItemsList/LinkedItem/LinkedItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQSLAReport/OverviewDQSLAReportSkeleton/OverviewDQSLAReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQTestReport/OverviewDQReportSkeleton/OverviewDQReportSkeleton.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewSkeleton/OverviewSkeleton.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItem.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocompleteStyles.ts
  odd-platform-ui/src/components/Search/Filters/FilterItem/SelectedFilterOption/SelectedFilterOption.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SelectedFilterOption/SelectedFilterOptionStyles.ts
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/Search/Filters/Filters.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewStyles.ts
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemStyles.ts
  odd-platform-ui/src/components/Search/Results/Results.tsx
  odd-platform-ui/src/components/Search/Results/ResultsStyles.ts
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeleton/SearchResultsSkeleton.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsSkeleton/SearchResultsSkeletonStyles.ts
  odd-platform-ui/src/components/Search/Results/SearchResultsTabs/SearchResultsTabs.tsx
  odd-platform-ui/src/components/Search/Results/SearchResultsTabs/SearchTabsSkeleton/SearchTabsSkeleton.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButton.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelectStyles.ts
  odd-platform-ui/src/components/shared/Icons/ColumnsIcon.tsx
  odd-platform-ui/src/components/shared/Icons/RowsIcon.tsx
  odd-platform-ui/src/components/shared/SkeletonWrapper/SkeletonWrapper.tsx
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCell.tsx
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenu.tsx
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellStyles.ts
  odd-platform-ui/src/lib/helpers.ts
  odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
Labels: scope: backend, scope: frontend, kind: feature

#1047 Markdown switched to light mode.
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
Labels: kind: enhancement, scope: frontend

#1059 Enhance odd-platform-enricher
  docker/injector/inject.py
  docker/injector/samples/test_ge_ingestion.json
Labels: kind: bug, scope: demo

#1060 Introduce ODD Profiler support
  .gitignore
  gradle/libs.versions.toml
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/LabelDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/LabelOrigin.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/LabelMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetFieldRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ReactiveLabelServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/IngestionService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/IngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/LabelIngestionServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_54__external_statistics_labels.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/BaseIngestionTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/DatasetIngestionTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/ExternalStatisticsIngestionTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/utils/IngestionModelGenerator.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/utils/IngestionModelMapper.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveDatasetFieldRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveDatasetVersionRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImplTest.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldStats/DatasetFieldStats.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldStats/DatsetFieldStatsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureTable.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDQSLAReport/OverviewDQSLAReport.tsx
  odd-platform-ui/src/redux/interfaces/datasetStructure.ts
Labels: kind: bug, scope: frontend
