Repository opendatadiscovery/odd-platform, pull requests merged in 2022-07, with the labels that each got.

#751 DatasetVersion reactive refactoring
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetVersionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveDatasetVersionRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImplTest.java
  odd-platform-ui/src/components/Management/Management.tsx
Labels: scope: backend

#778 Test coverage for DataSourceIngestionService
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceTest.java
Labels: scope: backend, kind: testing

#741 Now forms submitting on Enter.
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButton.tsx
  odd-platform-ui/src/components/shared/ConfirmationDialog/ConfirmationDialog.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
Labels: kind: enhancement, scope: frontend

#782 Data entity group form bug #779
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/EntityItem/EntityItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/AddDataEntityToGroupForm/AddDataEntityToGroupForm.tsx
  odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx
Labels: kind: bug, scope: frontend

#767 Separate the logic of the AppTextFiled component
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsFormItem/DatasetFieldEnumsFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTerms/AddTermsForm/TermsAutocomplete/TermsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipFormOwnerAutocomplete/OwnershipFormOwnerAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipFormRoleAutocomplete/OwnershipFormRoleAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateFormItem/LabelCreateFormItem.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceForm.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceList.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnerForm/OwnerForm.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormItem/TagCreateFormItem.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Overview/IdentityForm/Identity.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermLinkedItemsList/LinkedItemsList.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermMainSearch/TermMainSearch.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchFilters/TermSearchFilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchFilters/TermSearchFilterItem/SingleFilterItem/SingleFilterItem.tsx
  odd-platform-ui/src/components/shared/AppDatePicker/AppDatePicker.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
  odd-platform-ui/src/components/shared/AppInput/AppInput.tsx
  odd-platform-ui/src/components/shared/AppInput/AppInputStyles.ts
  odd-platform-ui/src/components/shared/AppSelect/AppSelect.tsx
  odd-platform-ui/src/components/shared/AppSelect/AppSelectStyles.ts
  odd-platform-ui/src/components/shared/Autocomplete/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx
  odd-platform-ui/src/components/shared/MainSearch/MainSearch.tsx
Labels: kind: bug, kind: enhancement, good first issue, scope: frontend

#806 Capture alert information and send it via webhooks
  .github/PULL_REQUEST_TEMPLATE.md
  gradle/libs.versions.toml
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/ODDPlatformConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/R2DBCConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationSubscriber.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationSubscriberStarter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationsProperties.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/PGConnectionFactory.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/AlertNotificationMessageProcessor.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/AlertSlackNotificationMessageBuilder.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/NotificationMessageBuilder.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/PostgresWALMessageProcessor.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/webhook/SlackWebhookSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/webhook/WebhookSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/wal/DecodedWALMessage.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/wal/PostgresWALMessageDecoder.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/controller/AlertControllerTest.java
Labels: kind: feature

#816 Support external tags
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityDetailsDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityDimensionsDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DatasetFieldDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/LabelDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/TagDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/ingestion/DataEntityIngestionDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/ingestion/EnrichedDataEntityIngestionDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/LabelMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/TagMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/ingestion/IngestionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ReactiveLabelService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ReactiveLabelServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/TagService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/TagServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/LabelIngestionService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/LabelIngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/TagIngestionService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/TagIngestionServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_47__add_tag_external_attribute.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveDatasetFieldRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveDatasetVersionRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/TagRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImplTest.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureKeyFieldLabel/DatasetStructureKeyFieldLabelStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTags.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/OverviewTagsStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormStyles.ts
  odd-platform-ui/src/components/Management/LabelsList/EditableLabelItem/EditableLabelItem.tsx
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItem.tsx
  odd-platform-ui/src/components/shared/Icons/SystemIcon.tsx
  odd-platform-ui/src/components/shared/LabelItem/LabelItem.tsx
  odd-platform-ui/src/components/shared/LabelItem/LabelItemStyles.ts
  odd-platform-ui/src/components/shared/TagItem/TagItem.tsx
  odd-platform-ui/src/components/shared/TagItem/TagItemStyles.ts
  odd-platform-ui/src/components/shared/TruncatedLabel/TruncatedLabel.tsx
  odd-platform-ui/src/components/shared/TruncatedLabel/TruncatedLabelMenu/TruncatedLabelMenu.tsx
  odd-platform-ui/src/theme/palette.ts
Labels: scope: backend, scope: frontend, kind: feature

#809 Fix pagination in management section #808
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/redux/reducers/collectors.slice.ts
  odd-platform-ui/src/redux/reducers/datasources.slice.ts
  odd-platform-ui/src/redux/reducers/labels.slice.ts
  odd-platform-ui/src/redux/reducers/namespace.slice.ts
  odd-platform-ui/src/redux/reducers/tags.slice.ts
Labels: kind: bug, scope: frontend

#804 Migrate Data quality tests section to Redux toolkit #790
  odd-platform-ui/src/components/App.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/TestRunsHistoryContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistoryContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewContainer.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemContainer.tsx
  odd-platform-ui/src/lib/hooks.ts
  odd-platform-ui/src/lib/interfaces.ts
  odd-platform-ui/src/redux/actions/dataEntityRun.actions.ts
  odd-platform-ui/src/redux/actions/dataQualityTest.actions.ts
  odd-platform-ui/src/redux/actions/index.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/dataEntityRuns.slice.ts
  odd-platform-ui/src/redux/reducers/dataQualityTest.slice.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/dataEntityRun.selector.ts
  odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/thunks/dataEntityRun.thunk.ts
  odd-platform-ui/src/redux/thunks/dataQualityTest.thunks.ts
  odd-platform-ui/src/redux/thunks/index.ts
Labels: kind: enhancement, scope: frontend

#833 Activity bug fixes.
  odd-platform-ui/src/components/Activity/ActivityResults/ActivityItem/ActivityItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityActivity/ActivityResults/ActivityItem/ActivityItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditFormStyles.ts
  odd-platform-ui/src/components/shared/Activity/ActivityFields/EnumsActivityField/EnumsActivityField.tsx
  odd-platform-ui/src/components/shared/Activity/ActivityFields/StringActivityField/StringActivityField.tsx
  odd-platform-ui/src/components/shared/AppPopover/AppPopover.tsx
  odd-platform-ui/src/components/shared/AppPopover/AppPopoverStyles.ts
  odd-platform-ui/src/components/shared/TruncatedLabel/TruncatedLabel.tsx
  odd-platform-ui/src/redux/reducers/activity.slice.ts
Labels: kind: bug, scope: frontend

#825 Improve Slack notification message and fix leakages
  docker/injector/inject.py
  docker/injector/start.sh
  gradle/libs.versions.toml
  odd-platform-api/build.gradle
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/ODDPlatformConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityTypeDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/alert/AlertTypeEnum.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationSubscriber.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationSubscriberStarter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/PGConnectionFactory.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/config/NotificationConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/config/NotificationsProperties.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/dto/AlertNotificationMessage.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/dto/DecodedWALMessage.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/dto/NotificationMessage.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/dto/OwnershipPair.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/exception/NotificationSenderException.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/exception/NotificationSubscriberException.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/AlertNotificationMessageProcessor.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/AlertSlackNotificationMessageBuilder.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/NotificationMessageBuilder.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/PostgresWALMessageProcessor.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/message/MrkdwnUtils.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/message/SlackEmojiUtils.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/message/SlackNotificationMessageGenerator.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/webhook/SlackWebhookSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/processor/webhook/WebhookSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/sender/AbstractNotificationSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/sender/NotificationSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/sender/SlackNotificationSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/sender/WebhookNotificationSender.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/translator/AlertNotificationMessageTranslator.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/translator/NotificationMessageTranslator.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/wal/DecodedWALMessage.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/wal/PostgresWALMessageDecoder.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqRecordHelper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/utils/JSONSerDeUtils.java
  odd-platform-api/src/main/resources/application.yml
Labels: kind: bug, kind: enhancement, scope: backend

#838 Unclosed statement in the notification subscriber thread
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationSubscriber.java
Labels: kind: bug

#842 Fix activity order
  odd-platform-ui/src/redux/reducers/activity.slice.ts
Labels: kind: bug, scope: frontend

#844 Alerts date fix
  odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
  odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTabsStyles.ts
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/lib/constants.ts
  odd-platform-ui/src/lib/helpers.ts
  odd-platform-ui/src/lib/redux/helpers.ts
  odd-platform-ui/src/redux/interfaces/alerts.ts
  odd-platform-ui/src/redux/interfaces/index.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/interfaces/termGroup.ts
  odd-platform-ui/src/redux/reducers/alerts.slice.ts
  odd-platform-ui/src/redux/thunks/alerts.thunks.ts
Labels: kind: bug, scope: frontend

#848 Replace SLA SVG HTML with the image
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataQualityController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/CachingByteArraySLAResourceResolver.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/SLAResourceResolver.java
  odd-platform-api/src/main/resources/sla/sla_green.png
  odd-platform-api/src/main/resources/sla/sla_red.png
  odd-platform-api/src/main/resources/sla/sla_yellow.png
  odd-platform-specification/openapi.yaml
Labels: kind: bug, kind: enhancement

#850 Rename severity statuses
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/sla/SLACalculator.java
  odd-platform-api/src/main/resources/db/migration/V0_0_50__rename_data_qa_severity.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/sla/SLACalculatorTest.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
Labels: scope: backend, scope: frontend

#858 Fix initial upsert in the statistics table
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityStatisticsRepositoryImpl.java
Labels: kind: bug, scope: backend

#860 Fix SLA images loading for an ARM platform
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/CachingByteArraySLAResourceResolver.java
Labels: kind: bug, scope: backend

#861 Remove tags/labels which doesn't have any relations
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepositoryImpl.java
Labels: kind: bug

#803 DatasetStructure refactoring to reactive approach
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetFieldApiMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetStructureRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetStructureRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetStructureRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetStructureRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetStructureService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetStructureServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/mapper/DatasetVersionMapperTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/ReactiveDatasetVersionRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DatasetStructureServiceImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImplTest.java
Labels: scope: backend, kind: optimization

#864 Incorrect update of counter on Activity page
  odd-platform-ui/src/components/Activity/Filters/Filters.tsx
Labels: kind: bug, scope: frontend

#870 Fix dataset labels update in case of multiple versions
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityFilledRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityFilledRepositoryImpl.java
Labels: kind: bug, scope: backend

#872 Add filter by users to activity feed
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveActivityRepositoryImpl.java
  odd-platform-ui/src/components/Activity/Filters/Filters.tsx
Labels: kind: bug, scope: backend, scope: frontend

#877 Fix Ingestion API performance bug
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractCRUDRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqReactiveOperations.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetFieldServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetStructureServiceImpl.java
Labels: kind: bug, scope: backend
