Repository opendatadiscovery/odd-platform, pull requests merged in 2022-03, with the labels that each got.

#493 Enhancement/cleaning overrides
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStyles.ts
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemStyles.ts
  odd-platform-ui/src/components/shared/AppCircularProgress/AppCircularProgressStyles.ts
  odd-platform-ui/src/components/shared/AppMenu/AppMenuStyles.ts
  odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItem.tsx
  odd-platform-ui/src/components/shared/AppPaper/AppPaper.tsx
  odd-platform-ui/src/components/shared/AppPaper/AppPaperStyles.tsx
  odd-platform-ui/src/components/shared/AppRadio/AppRadio.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTab/AppLinkTab.tsx
  odd-platform-ui/src/components/shared/AppTabs/AppTab/AppTab.tsx
  odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapperStyles.ts
  odd-platform-ui/src/index.tsx
  odd-platform-ui/src/theme/overrides.ts
Labels: kind: enhancement, scope: frontend

#511 Align data source collector request with the latest ODD Spec
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
Labels: kind: bug, scope: backend

#502 [Backend] - Ownership Refactoring. Initial commit
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnerService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnerServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/RoleService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/RoleServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImplTest.java
Labels: kind: enhancement, scope: backend

#492 [Backend] - Owner Integration tests. Initial commit
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/OwnerRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/RolesRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImplTest.java
Labels: kind: enhancement, scope: backend

#491 Unit tests for IngestionService
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/utils/JSONTestUtils.java
  odd-platform-api/src/test/resources/fixtures/ingestion/dag/dag.json
  odd-platform-api/src/test/resources/fixtures/ingestion/dag/lineage.json
Labels: scope: backend, enhancement

#445 Add tokens
  odd-platform-api/gradle.properties
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/filter/AbstractIngestionFilter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/filter/IngestionDataEntitiesFilter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/filter/IngestionDataSourceFilter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/CollectorController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataSourceController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/CollectorDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataSourceDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/TokenDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/CollectorMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/CollectorMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataSourceMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataSourceMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/NamespaceMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/NamespaceMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/TokenMapper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/TokenMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/ingestion/DataSourceIngestionMapperImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/CollectorRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/CollectorRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TokenRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TokenRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/CollectorService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/CollectorServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/TokenService.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/TokenServiceImpl.java
  odd-platform-api/src/main/resources/db/migration/V0_0_28__add_token.sql
  odd-platform-api/src/main/resources/db/migration/V0_0_29__add_collector.sql
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/CollectorRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImplTest.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceTest.java
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemToken/DataSourceItemToken.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemToken/DataSourceItemTokenContainer.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemToken/DataSourceItemTokenStyles.ts
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceSkeletonItem/DataSourceSkeletonItem.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListContainer.tsx
  odd-platform-ui/src/components/shared/EntityTypeItem/__tests__/EntityTypeItem.test.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
  odd-platform-ui/src/redux/actions/datasource.actions.ts
  odd-platform-ui/src/redux/reducers/datasources.reducer.ts
  odd-platform-ui/src/redux/thunks/datasources.thunks.ts
Labels: scope: backend, scope: frontend, kind: feature, enhancement

#516 add condition to filters
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/filter/IngestionDataEntitiesFilter.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/filter/IngestionDataSourceFilter.java
  odd-platform-api/src/main/resources/application.yml
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImplTest.java
Labels: kind: enhancement, scope: backend

#486 Do not run frontend tests if no FE files have been changed
  odd-platform-ui/.husky/.gitignore
  odd-platform-ui/.husky/pre-commit
  odd-platform-ui/package.json
Labels: scope: frontend, kind: chore, kind: maintenance

#519 Update README contacts' list
  README.md
Labels: kind: chore, scope: documentation

#517 Collector frontend
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorFormContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorFormStyles.ts
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocompleteContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItem.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemStyles.ts
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemToken.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemTokenContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemTokenStyles.ts
  odd-platform-ui/src/components/Management/CollectorsList/CollectorSkeletonItem/CollectorSkeletonItem.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsList.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsListContainer.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsListStyles.ts
  odd-platform-ui/src/components/Management/Management.tsx
  odd-platform-ui/src/redux/actions/collector.actions.ts
  odd-platform-ui/src/redux/actions/index.ts
  odd-platform-ui/src/redux/interfaces/collectors.ts
  odd-platform-ui/src/redux/interfaces/index.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/reducers/collectors.reducer.ts
  odd-platform-ui/src/redux/reducers/index.ts
  odd-platform-ui/src/redux/selectors/collectors.selectors.ts
  odd-platform-ui/src/redux/thunks/collectors.thunks.ts
  odd-platform-ui/src/redux/thunks/index.ts
Labels: scope: frontend, kind: feature, enhancement

#520 Updated frontend packages.
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescriptionStyles.ts
  odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
Labels: kind: enhancement, scope: frontend

#526 Fix husky run on CI
  odd-platform-ui/.husky/prepare.sh
  odd-platform-ui/package.json
Labels: kind: maintenance, bug

#533 Fix husky run locally in case when husky is not installed previously
  odd-platform-ui/.husky/prepare.sh
  odd-platform-ui/package.json
Labels: kind: bug, kind: maintenance

#531 Fixed lineage bug.
  odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLink.tsx
  odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
Labels: kind: bug, scope: frontend, bug

#529 updating packages for dependabot
  odd-platform-ui/package.json
Labels: kind: enhancement, scope: frontend
