Repository opendatadiscovery/odd-platform, pull requests merged in 2023-09, with the labels that each got.

#1415 Fix migration
  odd-platform-api/src/main/resources/db/migration/V0_0_81__dataset_field_internal_name.sql
Labels: kind: bug

#1418 Translation fix
  odd-platform-ui/src/locales/i18n.ts
Labels: kind: bug

#1420 Locales fix.
  odd-platform-ui/src/locales/i18n.ts
Labels: kind: bug

#1421 Tabs bugfix.
  odd-platform-ui/src/components/App.tsx
  odd-platform-ui/src/components/shared/elements/AppTabs/AppTabs.tsx
  odd-platform-ui/src/components/shared/elements/AppToolbar/ToolbarTabs/ToolbarTabs.tsx
  odd-platform-ui/src/locales/translations/fr.json
Labels: kind: bug

#1427 Warn the user before closing modal windows
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroup/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldEnumsForm/DatasetFieldEnumsForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldLabelsForm/DatasetFieldLabelsForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/HierarchyLineage/ZoomableLineage/LineageGraph/Node/Info/GroupedEntitiesListModal/GroupedEntitiesListModal.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/SaveFilesForm/SaveFilesForm.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
  odd-platform-ui/src/components/shared/elements/DialogWrapper/DialogWrapper.tsx
  odd-platform-ui/src/lib/helpers.ts
  odd-platform-ui/src/locales/translations/ch.json
  odd-platform-ui/src/locales/translations/en.json
  odd-platform-ui/src/locales/translations/fr.json
  odd-platform-ui/src/locales/translations/hy.json
Labels: scope: frontend, kind: feature

#1441 Input component refactoring
  odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/CreateMessageForm/CreateMessageForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldEnumsForm/DatasetFieldEnumsFormItem/DatasetFieldEnumsFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldLabelsForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetStructureHeader/DatasetStructureHeader.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/EditLinkForm/EditLinkForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/SaveLinksForm/LinkItem/LinkItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/Integrations/IntegrationPreviewList/IntegrationPreviewList.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateFormItem/LabelCreateFormItem.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelsList.tsx
  odd-platform-ui/src/components/Management/OwnerAssociations/OwnerAssociationsHeader/OwnerAssociationsHeader.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnerForm/OwnerForm.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/PolicyList/PolicyDetails/PolicyForm/PolicyForm.tsx
  odd-platform-ui/src/components/Management/PolicyList/PolicyList.tsx
  odd-platform-ui/src/components/Management/RolesList/RoleForm/RoleForm.tsx
  odd-platform-ui/src/components/Management/RolesList/RolesList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateFormItem/TagCreateFormItem.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Overview/OwnerAssociation/OwnerAssociationForm/OwnerAssociationForm.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/TermLinkedItemsList/LinkedItemsList.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchFilters/TermSearchFilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/shared/elements/AppInput/AppInput.tsx
  odd-platform-ui/src/components/shared/elements/AppInput/AppInputStyles.ts
  odd-platform-ui/src/components/shared/elements/Input/Input.styles.ts
  odd-platform-ui/src/components/shared/elements/Input/Input.tsx
  odd-platform-ui/src/components/shared/elements/index.ts
  odd-platform-ui/src/locales/translations/en.json
Labels: kind: enhancement, scope: frontend
