Repository opendatadiscovery/odd-platform, pull requests merged in 2023-10, with the labels that each got.

#1450 chore: minor css fixes for roles and polices managment page
  odd-platform-ui/pnpm-lock.yaml
  odd-platform-ui/src/components/Management/PolicyList/PolicyItem/PolicyItem.tsx
  odd-platform-ui/src/components/Management/RolesList/RoleItem/RoleItem.tsx
Labels: kind: bug

#1448 Lists scroll improvements [Management page].
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsList.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorsListStyles.ts
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesList.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourcesListStyles.ts
  odd-platform-ui/src/components/Management/Integrations/IntegrationPreviewList/IntegrationPreviewList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceList.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListSkeleton/NamespaceListSkeleton.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceListStyles.ts
  odd-platform-ui/src/components/Management/OwnerAssociations/OwnerAssociationsList/OwnerAssociationsNew/OwnerAssociationsNew.tsx
  odd-platform-ui/src/components/Management/OwnerAssociations/OwnerAssociationsList/OwnerAssociationsResolved/OwnerAssociationsResolved.tsx
  odd-platform-ui/src/components/Management/OwnersList/EditableOwnerItem/EditableOwnerItem.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersList.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnersListStyles.ts
  odd-platform-ui/src/components/Management/RolesList/RolesList.tsx
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItem.tsx
  odd-platform-ui/src/components/Management/TagsList/EditableTagItem/EditableTagItemStyles.ts
  odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
  odd-platform-ui/src/components/Management/TagsList/TagsListStyles.ts
  odd-platform-ui/src/components/shared/elements/StyledComponents/ScrollableContainer.ts
  tests/ui/pages/management/owners-page.ts
Labels: kind: enhancement, scope: frontend

#1465 (bugfix): correct rendering terms' markdown on dataset structure page
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldTerms/TermItem/TermItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTerms/TermItem/TermItem.tsx
  odd-platform-ui/src/components/shared/elements/forms/AssignTermForm/AssignTermForm.tsx
  odd-platform-ui/src/lib/hooks/api/terms.ts
Labels: kind: bug, scope: frontend

#1488 Dependencies: upgrade react-query from 4 to 5
  odd-platform-ui/package.json
  odd-platform-ui/pnpm-lock.yaml
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureCompare/DatasetStructureCompare.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldHeader/DatasetFieldInternalNameForm/DatasetFieldInternalNameForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldTerms/AssignFieldTermForm/AssignFieldTermForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/EditLinkForm/EditLinkForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/SaveFilesForm/SaveFilesForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/SaveLinksForm/SaveLinksForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupItems/OverviewEntityGroupItems.tsx
  odd-platform-ui/src/components/Directory/DataSourceList/DataSourceList.tsx
  odd-platform-ui/src/components/Directory/Directory/Directory.tsx
  odd-platform-ui/src/components/Directory/Entities/Entities.tsx
  odd-platform-ui/src/components/Directory/Entities/EntitiesList/EntitiesList.tsx
  odd-platform-ui/src/components/Management/Integrations/IntegrationPreviewList/IntegrationPreviewList.tsx
  odd-platform-ui/src/components/shared/elements/AppErrorPage/AppErrorPage.tsx
  odd-platform-ui/src/components/shared/elements/EntityStatus/StatusSettingsForm/StatusSettingsForm.tsx
  odd-platform-ui/src/index.tsx
  odd-platform-ui/src/lib/hooks/api/dataEntity.ts
  odd-platform-ui/src/lib/hooks/api/dataEntityAttachments/dataEntityFiles.ts
  odd-platform-ui/src/lib/hooks/api/dataEntityAttachments/dataEntityLinks.ts
  odd-platform-ui/src/lib/hooks/api/datasetField.ts
  odd-platform-ui/src/lib/hooks/api/directory.ts
  odd-platform-ui/src/lib/hooks/api/integration.ts
  odd-platform-ui/src/lib/hooks/api/terms.ts
  odd-platform-ui/src/lib/interfaces/shared.ts
  odd-platform-ui/src/redux/lib/handleResponseThunk.ts
Labels: scope: frontend, kind: maintenance
