Repository opendatadiscovery/odd-platform, pull requests merged in 2023-11, with the labels that each got.

#1487 Infra: Implement monthly CVE checks workflow
  .github/workflows/cve.yaml
Labels: kind: feature, scope: infrastructure, hacktoberfest-accepted

#1493 Infra: Implement security policy
  SECURITY.md
Labels: kind: documentation, scope: infrastructure, hacktoberfest-accepted

#1494 Add issue template config
  .github/ISSUE_TEMPLATE/config.yml
Labels: scope: infrastructure, hacktoberfest-accepted

#1508 Fix Readme: change reference from master to main branch for odd charts
  README.md
Labels: kind: bug, kind: documentation, kind: feature

#1521 1520 - fix overwriting internal metadata by the collectors
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/MetadataIngestionRequestProcessor.java
Labels: kind: bug

#1516 Update ReadMe with info to run as separate container
  README.md
Labels: kind: documentation, kind: feature
