Repository opendatadiscovery/odd-platform, pull requests merged in 2023-01, with the labels that each got.

#1205 Support ODD IAM OAuth provider
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/ODDOAuth2Properties.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/Provider.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/condition/ODDIAMCondition.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/handler/impl/ODDIAMUserHandler.java
Labels: kind: feature

#1209 Fixed badges
  README.md
Labels: kind: bug, kind: documentation

#1210 Updated readme
  README.md
Labels: kind: documentation

#1214 Add ODD IAM Logout handler
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/auth/logout/ODDIAMLogoutSuccessHandler.java
Labels: kind: feature

#1215 Update integrations list
  README.md
Labels: kind: documentation

#1217 Additional links configuration
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/AdditionalLinkConfiguration.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/properties/AdditionalLinkProperties.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/LinksController.java
  odd-platform-specification/components.yaml
  odd-platform-specification/openapi.yaml
  odd-platform-ui/src/components/shared/AppToolbar/AppInfoMenu/AppInfoMenu.tsx
  odd-platform-ui/src/components/shared/AppToolbar/AppInfoMenu/AppInfoMenuStyles.ts
  odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
  odd-platform-ui/src/redux/actions/appInfo.actions.ts
  odd-platform-ui/src/redux/interfaces/state.ts
  odd-platform-ui/src/redux/selectors/appInfo.selectors.ts
  odd-platform-ui/src/redux/slices/appInfo.slice.ts
  odd-platform-ui/src/redux/thunks/appInfo.thunks.ts
Labels: kind: feature

#1224 Fix LinkedUrlList for DataQualityTests
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityDimensionsDto.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/attributes/DataQualityTestAttributes.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/attributes/LinkedUrlAttribute.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/AlertIngestionTest.java
  odd-platform-specification/components.yaml
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewExpectations/OverviewExpectations.tsx
  odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButton.tsx
  odd-platform-ui/src/components/shared/AppButton/AppButtonStyles.ts
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCell.tsx
  odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenu.tsx
Labels: kind: bug, scope: backend, scope: frontend, func: User API
