Repository opendatadiscovery/odd-platform, pull requests merged in 2023-03, with the labels that each got.

#1263 Fixed bug with empty metrics in structure
  odd-platform-ui/package-lock.json
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetFieldOverview/DatasetFieldMetrics/DatasetFieldMetrics.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetFieldOverview/DatasetFieldOverview.tsx
Labels: kind: bug, scope: frontend, func: User API

#1264 Add validation to Data Source Ingestion API
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/exception/ControllerAdvice.java
Labels: kind: bug

#1266 Metrics bugfix
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/metric/MetricPointRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/metric/MetricPointRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/metric/InternalIngestionMetricsServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/MetricsIngestionTest.java
Labels: kind: bug

#1268 Metrics bugfix + test enhancement
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/metric/InternalIngestionMetricsServiceImpl.java
  odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/MetricsIngestionTest.java
  odd-platform-api/src/test/resources/metrics/gauge_and_count.json
  odd-platform-api/src/test/resources/metrics/histogram_and_summary.json
Labels: kind: bug

#1274 React upgraded to v18
  odd-platform-ui/babel.config.js
  odd-platform-ui/jest.config.js
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/Activity/ActivityResults/ActivityItem/ActivityItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/CreateMessageForm/CreateMessageForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityActivity/ActivityResults/ActivityItem/ActivityItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/DataEntityGroup/DataEntityGroupForm/DataEntityGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetFieldOverview/DatasetFieldDescriptionForm/DatasetFieldDescriptionForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetFieldOverview/DatasetFieldEnumsForm/DatasetFieldEnumsForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetFieldOverview/DatasetFieldLabelsForm/DatasetFieldLabelsForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetFieldOverview/DatasetFieldLabelsForm/LabelsAutocomplete/LabelsAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetFieldOverview/DatasetFieldOverview.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureView/DatasetStructureHeader/DatasetStructureTypeCounts/DatasetStructureTypeCounts.tsx
  odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/StructureContext/StructureProvider.tsx
  odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
  odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/LineageContext/LineageProvider.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OwnersSection/OwnershipForm/OwnershipForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/AddDataEntityToGroupForm/AddDataEntityToGroupForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTerms/AddTermsForm/AddTermsForm.tsx
  odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTerms/AddTermsForm/TermsAutocomplete/TermsAutocomplete.tsx
  odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
  odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelCreateForm/LabelCreateForm.tsx
  odd-platform-ui/src/components/Management/LabelsList/LabelEditForm/LabelEditForm.tsx
  odd-platform-ui/src/components/Management/NamespaceList/NamespaceForm/NamespaceForm.tsx
  odd-platform-ui/src/components/Management/OwnerAssociations/OwnerAssociationsStore/OwnerAssociationsProvider.tsx
  odd-platform-ui/src/components/Management/OwnersList/OwnerForm/OwnerForm.tsx
  odd-platform-ui/src/components/Management/RolesList/RoleForm/RoleForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
  odd-platform-ui/src/components/Management/TagsList/TagEditForm/TagEditForm.tsx
  odd-platform-ui/src/components/Search/Filters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
  odd-platform-ui/src/components/Terms/TermDetails/Ownership/OwnershipForm.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx
  odd-platform-ui/src/components/Terms/TermSearch/TermSearchFilters/TermSearchFilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/shared/AppInput/AppInput.tsx
  odd-platform-ui/src/components/shared/AppSuspenseWrapper/AppSuspenseWrapper.tsx
  odd-platform-ui/src/components/shared/Autocomplete/NamespaceAutocomplete/NamespaceAutocomplete.tsx
  odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
  odd-platform-ui/src/components/shared/RestrictedRoute/RestrictedRoute.tsx
  odd-platform-ui/src/components/shared/WithFeature/WithFeature.tsx
  odd-platform-ui/src/components/shared/contexts/Permission/PermissionProvider.tsx
  odd-platform-ui/src/components/shared/contexts/Permission/WithPermissions.tsx
  odd-platform-ui/src/components/shared/contexts/Permission/WithPermissionsProvider.tsx
  odd-platform-ui/src/index.tsx
  odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
  odd-platform-ui/src/redux/selectors/datasources.selectors.ts
  odd-platform-ui/src/redux/selectors/owners.selectors.ts
  odd-platform-ui/src/redux/selectors/terms.selectors.ts
  odd-platform-ui/tsconfig.json
Labels: kind: enhancement, scope: frontend, func: User API

#1277 New FE test environment
  .github/workflows/sonar-frontend.yaml
  odd-platform-ui/package-lock.json
  odd-platform-ui/package.json
  odd-platform-ui/src/components/shared/BooleanFormatted/BooleanFormatted.tsx
  odd-platform-ui/src/components/shared/BooleanFormatted/__tests__/BooleanFormatted.test.tsx
  odd-platform-ui/src/components/shared/EntityClassItem/__tests__/EntityClassItem.test.tsx
  odd-platform-ui/src/components/shared/NumberFormatted/NumberFormatted.tsx
  odd-platform-ui/src/components/shared/NumberFormatted/__tests__/NumberFormatted.test.tsx
  odd-platform-ui/src/lib/hooks/useQueryParams.ts
  odd-platform-ui/src/lib/testHelpers.tsx
  odd-platform-ui/src/setupTests.ts
  odd-platform-ui/vite.config.ts
Labels: kind: enhancement, scope: frontend, kind: testing, func: User API

#1294 Fix stack overflow error
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveMetadataFieldRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/DatasetFieldMetadataIngestionServiceImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/HollowDataEntityIngestionRequestProcessor.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/IngestionProcessingPhase.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/MetadataIngestionRequestProcessor.java
Labels: kind: bug
