Repository opendatadiscovery/odd-platform, pull requests merged in 2024-02, with the labels that each got.

#1607 fix(odd-platform-ui): fix ui build for windows
  odd-platform-ui/README.md
  odd-platform-ui/generate.sh
  odd-platform-ui/package.json
Labels: kind: bug, kind: documentation, scope: frontend

#1610 Update README.md
  README.md
Labels: kind: documentation, kind: feature

#1615 fix getRelationships API when using query param
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRelationshipRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRelationshipRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveRelationshipsRepository.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveRelationshipsRepositoryImpl.java
  odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/RelationshipsServiceImpl.java
Labels: kind: bug

#1621 hotfix: fetch policy schema
  odd-platform-ui/src/redux/thunks/policy.thunks.ts
Labels: kind: bug

#1614 1590-1
  odd-platform-ui/package.json
  odd-platform-ui/pnpm-lock.yaml
  odd-platform-ui/src/components/DataQuality/DataQuality.styles.ts
  odd-platform-ui/src/components/DataQuality/DataQuality.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityContent.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/DataQualityFilters.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/DataQualityFiltersStyles.ts
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/DatasourceFilter.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/MultipleFilterItem/MultipleFilterItem.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocomplete.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/MultipleFilterItem/MultipleFilterItemAutocomplete/MultipleFilterItemAutocompleteStyles.ts
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/MultipleFilterItem/SelectedFilterOption/SelectedFilterOption.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/MultipleFilterItem/SelectedFilterOption/SelectedFilterOptionStyles.ts
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/NamespaceFilter.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/OwnerFIlter.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/TagFilter.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/FilterItem/TitleFilter.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityFilters/hooks/index.ts
  odd-platform-ui/src/components/DataQuality/DataQualityStore/DataQualityProvider.tsx
  odd-platform-ui/src/components/DataQuality/DataQualityStore/DataQualityStore.ts
  odd-platform-ui/src/components/DataQuality/interfaces.ts
  odd-platform-ui/src/lib/hooks/api/dataQuality.ts
  odd-platform-ui/src/lib/hooks/api/datasource.ts
  odd-platform-ui/src/lib/hooks/api/namespace.ts
  odd-platform-ui/src/lib/hooks/api/owner.ts
  odd-platform-ui/src/lib/hooks/api/tag.ts
  odd-platform-ui/src/lib/hooks/api/title.ts
  odd-platform-ui/src/locales/translations/en.json
Labels: scope: frontend

#1634 Update README.md
  README.md
Labels: kind: documentation

#1641 add airflow integration to readme
  README.md
  odd-platform-ui/public/imgs/airflow2.png
Labels: kind: documentation

#1645 bugfix(WithPermissions): check specific provided permission on `renderContent`.
  odd-platform-ui/src/components/shared/contexts/Permission/WithPermissions.tsx
  odd-platform-ui/src/lib/hooks/usePermissions.ts
Labels: kind: bug
